/**
 * Catalog expansion 6 — the verified bench lands (2026-07-25 attended run).
 *
 * 32 bars: expansion-4 bench (23 after ardesia dedupe) + expansion-5
 * bench (9, minus mercury-bar-west — parked on Google's
 * CLOSED_PERMANENTLY flag, see BENCH-STAGING doc) + sonnys-corner
 * (ex-Pencil Factory successor). Every bar web-verified open AND
 * Places-dry-run ground-truthed the same day (33/33 resolved; the
 * madelines@113-Franklin conflict resolved in its favor — it succeeded
 * Sereneco in the ex-Ramona space, 2023).
 *
 * Registered in bars.ts + catalog.slim.ts + refresh-places BAR_FILES +
 * review-mining-apply BAR_FILES (the four-way lockstep rule).
 */
import type { Bar } from '@/types';

export const expansion6Bars: Bar[] = [
  { id: 'bar-americano', name: 'Bar Americano', neighborhood: 'Greenpoint', address: '180 Franklin St, Brooklyn', lat: 40.732, lng: -73.9587, priceTier: 3, tags: ['cocktail', 'wine', 'date', 'polished', 'chill', 'pricey'], blurb: 'Vermouth on tap, spritzes, brass and leather. Aperitivo hour like Milan, corner of Franklin.', lastVerified: '2026-07-25' },
  { id: 'madelines', name: 'Madeline\'s', neighborhood: 'Greenpoint', address: '113 Franklin St, Brooklyn', lat: 40.7296, lng: -73.9578, priceTier: 3, tags: ['cocktail', 'buzzy', 'trendy', 'instagrammable', 'date', 'pricey'], blurb: 'Soaring ex-pencil-factory cocktail hall — 40-foot bar, mezzanine, DJ booth, Frenchy comfort food.', lastVerified: '2026-07-25' },
  { id: 'hide-and-seek', name: 'Hide & Seek', neighborhood: 'Greenpoint', address: '593 Manhattan Ave, Brooklyn', lat: 40.7236, lng: -73.9506, priceTier: 2, tags: ['chill', 'cocktail', 'wine', 'indie', 'live', 'mid'], blurb: 'Plant-filled café by day; cocktails, old-world wine, and weekend DJs after dark.', lastVerified: '2026-07-25' },
  { id: 'sonnys-corner', name: 'Sonny\'s Corner', neighborhood: 'Greenpoint', address: '142 Franklin St, Brooklyn', lat: 40.7303, lng: -73.9584, priceTier: 2, tags: ['locals', 'buzzy', 'loud', 'cocktail', 'mid'], blurb: 'New corner bar in the old Pencil Factory: frozen piña coladas, hot ham-and-cheese, packed nightly.', lastVerified: '2026-07-25' },
  { id: 'amity-hall-uptown', name: 'Amity Hall Uptown', neighborhood: 'UWS', address: '982 Amsterdam Ave', lat: 40.8016, lng: -73.9629, priceTier: 2, tags: ['beer', 'pub', 'loud', 'locals', 'mid'], blurb: 'Columbia\'s game-day den — long tap list, wall of screens, student-loud on weekends.', lastVerified: '2026-07-25' },
  { id: 'the-hoptimist', name: 'The Hoptimist', neighborhood: 'UWS', address: '422 Amsterdam Ave', lat: 40.7846, lng: -73.9777, priceTier: 2, tags: ['beer', 'chill', 'locals', 'post-work', 'mid'], blurb: 'Rotating craft taps and zero attitude on a beer-starved stretch of Amsterdam.', lastVerified: '2026-07-25' },
  { id: 'westland-roe', name: 'Westland Roe', neighborhood: 'UWS', address: '174 W 72nd St', lat: 40.7784, lng: -73.9815, priceTier: 2, tags: ['pub', 'beer', 'locals', 'post-work', 'mid'], blurb: 'Dublin-warm pub in an 1886 rowhouse; game audio on, kitchen until 3am.', lastVerified: '2026-07-25' },
  { id: 'purgatory', name: 'Purgatory', neighborhood: 'Bushwick', address: '675 Central Ave, Brooklyn', lat: 40.6872341, lng: -73.9057389, priceTier: 1, tags: ['dive', 'dance', 'indie', 'locals', 'cheap'], blurb: 'Queer-run Bushwick haunt: drag, dance parties, and stiff cheap pours till late.', lastVerified: '2026-07-25' },
  { id: 'carousel', name: 'Carousel', neighborhood: 'Bushwick', address: '36 Wyckoff Ave, Brooklyn', lat: 40.7068, lng: -73.9228, priceTier: 2, tags: ['lounge', 'dance', 'trendy', 'instagrammable', 'buzzy', 'mid'], blurb: 'Seventies conversation pits, pool tables, and DJs orbiting a carousel-shaped central bar.', lastVerified: '2026-07-25' },
  { id: 'rebeccas', name: 'Rebecca\'s', neighborhood: 'Bushwick', address: '610 Bushwick Ave, Brooklyn', lat: 40.698215, lng: -73.9342007, priceTier: 1, tags: ['dive', 'dance', 'locals', 'loud', 'cheap'], blurb: 'No-frills Bushwick standby — cheap drinks, DJs, and a sweaty little dance floor.', lastVerified: '2026-07-25' },
  { id: 'club-cumming', name: 'Club Cumming', neighborhood: 'East Village', address: '505 E 6th St', lat: 40.7254, lng: -73.98338, priceTier: 2, tags: ['dance', 'live', 'buzzy', 'loud', 'indie', 'mid'], blurb: 'Alan Cumming\'s tiny cabaret den — piano belters, drag, and \'90s dance chaos till late.', lastVerified: '2026-07-25' },
  { id: 'the-scratcher', name: 'The Scratcher', neighborhood: 'East Village', address: '209 E 5th St', lat: 40.72755, lng: -73.99042, priceTier: 1, tags: ['dive', 'pub', 'chill', 'locals', 'live', 'cheap'], blurb: 'Candlelit below-street Irish snug, proper Guinness, Sunday trad sessions. Zero shamrock kitsch.', lastVerified: '2026-07-25' },
  { id: 'international-bar', name: 'International Bar', neighborhood: 'East Village', address: '102 1st Ave', lat: 40.72663, lng: -73.98661, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'old-nyc', 'rough'], blurb: 'Cheap pours, crusty regulars, one door down from the old spot. Dive royalty.', lastVerified: '2026-07-25' },
  { id: 'bar-veloce-chelsea', name: 'Bar Veloce', neighborhood: 'Chelsea', address: '176 7th Ave', lat: 40.74296, lng: -73.99617, priceTier: 2, tags: ['wine', 'chill', 'date', 'polished', 'mid'], blurb: 'Sleek Italian wine sliver — prosecco, panini, and a calm Chelsea date perch.', lastVerified: '2026-07-25' },
  { id: 'eagle-nyc', name: 'Eagle NYC', neighborhood: 'Chelsea', address: '554 W 28th St', lat: 40.7517058, lng: -74.0042924, priceTier: 2, tags: ['dance', 'rooftop', 'loud', 'rough', 'locals', 'mid'], blurb: 'Two floors of leather and cruising, roof deck on top. Sunday beer blast is legend.', lastVerified: '2026-07-25' },
  { id: 'fleur-room', name: 'The Fleur Room', neighborhood: 'Chelsea', address: '105 W 28th St', lat: 40.7462, lng: -73.99062, priceTier: 3, tags: ['rooftop', 'cocktail', 'lounge', 'instagrammable', 'trendy', 'pricey'], blurb: '35th-floor glass box with vintage disco ball and 360 skyline. Dress up for the scene.', lastVerified: '2026-07-25' },
  { id: 'stout-nyc-fidi', name: 'Stout NYC FiDi', neighborhood: 'FiDi', address: '90 John St', lat: 40.7081, lng: -74.00512, priceTier: 2, tags: ['beer', 'pub', 'post-work', 'loud', 'mid'], blurb: 'Huge tap list, wall of TVs, FiDi post-work roar. Sports-bar basics done big.', lastVerified: '2026-07-25' },
  { id: 'the-press-room', name: 'The Press Room', neighborhood: 'FiDi', address: '28 Liberty St', lat: 40.70862, lng: -74.00861, priceTier: 2, tags: ['beer', 'cocktail', 'chill', 'indie', 'mid'], blurb: '48 taps beside 60,000 vintage movie printing plates at Alamo Drafthouse. No ticket needed.', lastVerified: '2026-07-25' },
  { id: 'ryan-maguires', name: 'Ryan Maguire\'s', neighborhood: 'FiDi', address: '28 Cliff St', lat: 40.70933, lng: -74.00435, priceTier: 2, tags: ['pub', 'beer', 'locals', 'post-work', 'chill', 'mid'], blurb: 'Family-run Irish stalwart since \'95 — free happy-hour bites, Wednesday trivia regulars.', lastVerified: '2026-07-25' },
  { id: 'lanterns-keep', name: 'Lantern\'s Keep', neighborhood: 'Midtown', address: '49 W 44th St', lat: 40.75552, lng: -73.98194, priceTier: 3, tags: ['cocktail', 'lounge', 'polished', 'romantic', 'date', 'pricey'], blurb: 'Reborn March 2026 as Da Toscano\'s aperitivo bar — negronis, arancini, hotel-parlor hush.', lastVerified: '2026-07-25' },
  { id: 'nothing-really-matters', name: 'Nothing Really Matters', neighborhood: 'Midtown', address: '210 W 50th St', lat: 40.76158, lng: -73.9838, priceTier: 3, tags: ['cocktail', 'speakeasy', 'hiphop', 'date', 'trendy', 'pricey'], blurb: 'Cocktail den behind blacked-out windows inside the 1-train station. Disco ball, \'90s R&B.', lastVerified: '2026-07-25' },
  { id: 'treadwell-park', name: 'Treadwell Park', neighborhood: 'UES', address: '1125 1st Ave', lat: 40.7622, lng: -73.9612, priceTier: 2, tags: ['beer', 'pub', 'buzzy', 'post-work', 'chill', 'mid'], blurb: 'Twenty rotating taps, ping pong, giant pretzels. Summer-camp beer hall for the UES.', lastVerified: '2026-07-25' },
  { id: 'plug-uglies', name: 'Plug Uglies', neighborhood: 'UES', address: '1495 1st Ave', lat: 40.7719, lng: -73.9528, priceTier: 2, tags: ['pub', 'beer', 'locals', 'loud', 'post-work', 'mid'], blurb: 'Gramercy sports-pub transplant in the old Bar Coastal space. Shuffleboard, wings, game-day pints.', lastVerified: '2026-07-25' },
  { id: 'drunken-munkey', name: 'The Drunken Munkey', neighborhood: 'UES', address: '338 E 92nd St', lat: 40.7811, lng: -73.9482, priceTier: 3, tags: ['cocktail', 'date', 'romantic', 'polished', 'pricey'], blurb: 'Old Bombay cocktails and curry till midnight. Colonial-kitsch date spot done right.', lastVerified: '2026-07-25' },
  { id: 'the-waylon', name: 'The Waylon', neighborhood: "Hell's Kitchen", address: '736 10th Ave', lat: 40.7645, lng: -73.9925, priceTier: 2, tags: ['pub', 'live', 'locals', 'chill', 'mid'], blurb: 'Honky-tonk saloon pouring Shiner Bock and bourbon, country bands most nights.', lastVerified: '2026-07-25' },
  { id: 'pearl-box', name: 'Pearl Box', neighborhood: 'SoHo', address: '357 W Broadway', lat: 40.7228, lng: -74.0037, priceTier: 4, tags: ['cocktail', 'lounge', 'romantic', 'polished', 'instagrammable', 'splurge'], blurb: 'Mirrored stairs to a 70s-glam third floor: icy martinis, caviar weighed tableside.', lastVerified: '2026-07-25' },
  { id: '161-lafayette', name: '161 Lafayette', neighborhood: 'SoHo', address: '161 Lafayette St', lat: 40.7191, lng: -73.9995, priceTier: 1, tags: ['dive', 'loud', 'locals', 'indie', 'cheap'], blurb: 'Fifteen-seat karaoke hole-in-the-wall. Polaroid walls, cheap drinks, friends by song two.', lastVerified: '2026-07-25' },
  { id: 'alibi-lounge', name: 'Alibi Lounge', neighborhood: 'Harlem', address: '2376 Adam Clayton Powell Jr Blvd', lat: 40.8178209, lng: -73.9422219, priceTier: 2, tags: ['lounge', 'cocktail', 'locals', 'buzzy', 'dance', 'mid'], blurb: 'Black-owned Harlem LGBTQ lounge: sharp cocktails, drag nights, real neighborhood warmth.', lastVerified: '2026-07-25' },
  { id: 'the-wolfhound', name: 'The Wolfhound', neighborhood: 'Astoria', address: '38-14 30th Ave, Queens', lat: 40.7639277, lng: -73.9154228, priceTier: 2, tags: ['pub', 'beer', 'locals', 'live', 'chill', 'mid'], blurb: 'Proper Irish pub on 30th Ave: good Guinness, trad sessions, zero pretense.', lastVerified: '2026-07-25' },
  { id: 'olivers-astoria', name: 'Oliver\'s Astoria', neighborhood: 'Astoria', address: '37-19 Broadway, Queens', lat: 40.7563, lng: -73.9198, priceTier: 2, tags: ['beer', 'pub', 'chill', 'locals', 'date', 'mid'], blurb: 'Craft taps and elevated bar bites. Astoria\'s easygoing Broadway living room.', lastVerified: '2026-07-25' },
  { id: 'icon-bar', name: 'Icon Bar', neighborhood: 'Astoria', address: '31-84 33rd St, Queens', lat: 40.7599, lng: -73.9265, priceTier: 2, tags: ['lounge', 'dance', 'buzzy', 'locals', 'mid'], blurb: 'Astoria\'s gay stalwart: drag shows, DJs, strong pours under moody light.', lastVerified: '2026-07-25' },
  { id: 'record-room', name: 'Record Room', neighborhood: 'LIC', address: '47-09 Center Blvd, Queens', lat: 40.7443, lng: -73.9585, priceTier: 3, tags: ['cocktail', 'lounge', 'chill', 'date', 'indie', 'pricey'], blurb: 'Hi-fi vinyl spins over serious cocktails by the LIC waterfront. Listening-room calm.', lastVerified: '2026-07-25' },
];
