import type { Bar } from '@/types';

export const bars: Bar[] = [
  // LES
  {
    id: 'attaboy',
    name: 'Attaboy',
    neighborhood: 'LES',
    address: '134 Eldridge St',
    lat: 40.7188,
    lng: -73.9926,
    priceTier: 3,
    tags: ['cocktail', 'speakeasy', 'polished', 'industry', 'pricey'],
    blurb: 'No menu. Tell them what you like. They build it.',
  },
  {
    id: 'mr-purple',
    name: 'Mr. Purple',
    neighborhood: 'LES',
    address: '180 Orchard St',
    lat: 40.7211,
    lng: -73.9874,
    priceTier: 3,
    tags: ['rooftop', 'trendy', 'instagrammable', 'buzzy', 'pricey', 'house'],
    blurb: 'Rooftop with skyline views. Bring people to impress.',
  },
  {
    id: '169-bar',
    name: '169 Bar',
    neighborhood: 'LES',
    address: '169 East Broadway',
    lat: 40.7142,
    lng: -73.9890,
    priceTier: 1,
    tags: ['dive', 'rough', 'old-nyc', 'cheap', 'locals', 'indie'],
    blurb: 'Stuffed peacock on the wall. Cheap drinks. Anything goes.',
  },
  {
    id: 'welcome-johnsons',
    name: 'Welcome to the Johnsons',
    neighborhood: 'LES',
    address: '123 Rivington St',
    lat: 40.7202,
    lng: -73.9876,
    priceTier: 1,
    tags: ['dive', 'cheap', 'locals', 'rough', 'old-nyc', 'indie'],
    blurb: 'Wood paneling, sticky floors, jukebox. The original.',
  },
  {
    id: 'pianos',
    name: 'Pianos',
    neighborhood: 'LES',
    address: '158 Ludlow St',
    lat: 40.7212,
    lng: -73.9863,
    priceTier: 2,
    tags: ['live', 'buzzy', 'loud', 'mid', 'trendy'],
    blurb: 'Live music downstairs, packed bar upstairs. Always something.',
  },

  // East Village
  {
    id: 'death-and-co',
    name: 'Death & Co',
    neighborhood: 'East Village',
    address: '433 E 6th St',
    lat: 40.7256,
    lng: -73.9826,
    priceTier: 3,
    tags: ['cocktail', 'polished', 'date', 'pricey', 'industry'],
    blurb: 'Cocktail temple. Bring it for date night.',
  },
  {
    id: 'pdt',
    name: 'PDT',
    neighborhood: 'East Village',
    address: '113 St Marks Pl',
    lat: 40.7282,
    lng: -73.9844,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'polished', 'date', 'pricey'],
    blurb: 'Phone booth in a hot dog shop. You know the one.',
  },
  {
    id: 'amor-y-amargo',
    name: 'Amor y Amargo',
    neighborhood: 'East Village',
    address: '443 E 6th St',
    lat: 40.7256,
    lng: -73.9821,
    priceTier: 3,
    tags: ['cocktail', 'lounge', 'chill', 'industry', 'pricey'],
    blurb: 'Tiny bitters bar. Sit at the counter.',
  },
  {
    id: 'holiday-cocktail-lounge',
    name: 'Holiday Cocktail Lounge',
    neighborhood: 'East Village',
    address: '75 St Marks Pl',
    lat: 40.7280,
    lng: -73.9866,
    priceTier: 2,
    tags: ['cocktail', 'old-nyc', 'locals', 'mid', 'lounge'],
    blurb: 'Old St. Marks institution. Red walls, regulars, perfect drinks.',
  },
  {
    id: 'ace-bar',
    name: 'Ace Bar',
    neighborhood: 'East Village',
    address: '531 E 5th St',
    lat: 40.7257,
    lng: -73.9805,
    priceTier: 1,
    tags: ['dive', 'pub', 'cheap', 'locals', 'buzzy'],
    blurb: 'Pool tables, skee-ball, pinball, beer. No pretense.',
  },

  // Williamsburg
  {
    id: 'the-levee',
    name: 'The Levee',
    neighborhood: 'Williamsburg',
    address: '212 Berry St',
    lat: 40.7185,
    lng: -73.9612,
    priceTier: 1,
    tags: ['dive', 'cheap', 'locals', 'rough', 'pub'],
    blurb: 'Free cheese balls. $4 PBR + shot. Pool table.',
  },
  {
    id: 'maison-premiere',
    name: 'Maison Premiere',
    neighborhood: 'Williamsburg',
    address: '298 Bedford Ave',
    lat: 40.7155,
    lng: -73.9614,
    priceTier: 4,
    tags: ['cocktail', 'wine', 'romantic', 'polished', 'splurge', 'date'],
    blurb: 'Oysters and absinthe. New Orleans in Brooklyn.',
  },
  {
    id: 'donna',
    name: 'Donna',
    neighborhood: 'Williamsburg',
    address: '27 Broadway, Brooklyn',
    lat: 40.7106,
    lng: -73.9668,
    priceTier: 3,
    tags: ['cocktail', 'trendy', 'date', 'instagrammable', 'pricey'],
    blurb: 'Mediterranean cocktails. Dim lighting. Always full.',
  },
  {
    id: 'petes-candy-store',
    name: "Pete's Candy Store",
    neighborhood: 'Williamsburg',
    address: '709 Lorimer St',
    lat: 40.7204,
    lng: -73.9504,
    priceTier: 2,
    tags: ['live', 'indie', 'chill', 'mid', 'locals'],
    blurb: 'Free music every night. Tiny back room. Real talent.',
  },
  {
    id: 'skinny-dennis',
    name: 'Skinny Dennis',
    neighborhood: 'Williamsburg',
    address: '152 Metropolitan Ave',
    lat: 40.7152,
    lng: -73.9590,
    priceTier: 2,
    tags: ['dive', 'live', 'mid', 'buzzy', 'rough', 'indie'],
    blurb: 'Honky tonk in Brooklyn. Bluegrass nightly. Frozen Willies.',
  },
];
