import type { Bar } from '@/types';

/**
 * Catalog expansion — Manhattan depth + Brooklyn coverage.
 *
 * Sourced via the ingestion pipeline (scripts/ingest-bars.ts, OpenStreetMap),
 * then curated and vibe-tagged by hand. Coordinates come from OSM (real);
 * hours/specifics are best-effort and unverified — see PRD R4. `lastVerified`
 * is set to the ingest date so these pass the freshness filter; replace with a
 * real verification date as each is checked.
 */

const INGESTED = '2026-06-26';

export const extraBars: Bar[] = [
  // ---------- LES ----------
  {
    id: 'back-room',
    name: 'The Back Room',
    neighborhood: 'LES',
    address: '102 Norfolk St',
    lat: 40.7187462,
    lng: -73.9869705,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'old-nyc', 'date', 'lounge'],
    blurb: 'Prohibition-era speakeasy down an alley. Drinks still come in teacups.',
    lastVerified: INGESTED,
  },
  {
    id: 'double-chicken-please',
    name: 'Double Chicken Please',
    neighborhood: 'LES',
    address: '115 Allen St',
    lat: 40.719613,
    lng: -73.9906095,
    priceTier: 3,
    tags: ['cocktail', 'trendy', 'buzzy', 'industry', 'pricey'],
    blurb: 'Front room is a hang; the back makes some of the best cocktails on earth.',
    lastVerified: INGESTED,
  },
  {
    id: 'arlenes-grocery',
    name: "Arlene's Grocery",
    neighborhood: 'LES',
    address: '95 Stanton St',
    lat: 40.7213285,
    lng: -73.9883827,
    priceTier: 2,
    tags: ['live', 'indie', 'buzzy', 'cheap', 'locals'],
    blurb: 'Sticky-floor live music since the 90s. Monday rock-and-roll karaoke.',
    lastVerified: INGESTED,
  },
  {
    id: 'max-fish',
    name: 'Max Fish',
    neighborhood: 'LES',
    address: '120 Orchard St',
    lat: 40.719365,
    lng: -73.9893214,
    priceTier: 1,
    tags: ['dive', 'indie', 'cheap', 'locals', 'rough'],
    blurb: 'Lower East Side art-dive institution. Pinball, cheap beer, no attitude.',
    lastVerified: INGESTED,
  },
  {
    id: 'mehanata',
    name: 'Mehanata Bulgarian Bar',
    neighborhood: 'LES',
    address: '113 Ludlow St',
    lat: 40.7194872,
    lng: -73.9888931,
    priceTier: 2,
    tags: ['dance', 'loud', 'buzzy', 'indie', 'trendy'],
    blurb: 'Bulgarian party bar with a vodka ice room and a gypsy-punk dance floor.',
    lastVerified: INGESTED,
  },

  // ---------- East Village ----------
  {
    id: 'dba',
    name: 'd.b.a.',
    neighborhood: 'East Village',
    address: '41 1st Ave',
    lat: 40.7243458,
    lng: -73.9880125,
    priceTier: 2,
    tags: ['beer', 'garden', 'locals', 'chill', 'mid'],
    blurb: 'Cask ales, rare whiskeys, and a back garden. A beer-geek temple since 1994.',
    lastVerified: INGESTED,
  },
  {
    id: 'burp-castle',
    name: 'Burp Castle',
    neighborhood: 'East Village',
    address: '41 E 7th St',
    lat: 40.7283251,
    lng: -73.9886573,
    priceTier: 2,
    tags: ['beer', 'chill', 'indie', 'locals', 'mid'],
    blurb: 'Belgian beer temple where the painted monks shush you to a whisper.',
    lastVerified: INGESTED,
  },
  {
    id: 'vazacs',
    name: "Vazac's Horseshoe Bar",
    neighborhood: 'East Village',
    address: '108 Avenue B',
    lat: 40.7250128,
    lng: -73.9813915,
    priceTier: 1,
    tags: ['dive', 'old-nyc', 'cheap', 'locals', 'rough'],
    blurb: 'The Horseshoe Bar — a film-set dive on Tompkins Square. Cash and character.',
    lastVerified: INGESTED,
  },
  {
    id: 'niagara',
    name: 'Niagara',
    neighborhood: 'East Village',
    address: '112 Avenue A',
    lat: 40.725928,
    lng: -73.9834617,
    priceTier: 1,
    tags: ['dive', 'indie', 'buzzy', 'locals', 'cheap'],
    blurb: 'Rock-and-roll corner dive with a tiki basement and a punk pedigree.',
    lastVerified: INGESTED,
  },
  {
    id: 'ottos-shrunken-head',
    name: "Otto's Shrunken Head",
    neighborhood: 'East Village',
    address: '538 E 14th St',
    lat: 40.7294241,
    lng: -73.9787003,
    priceTier: 1,
    tags: ['dive', 'indie', 'loud', 'buzzy', 'cheap'],
    blurb: 'Tiki dive with punk shows in the back and strong, cheap mai tais.',
    lastVerified: INGESTED,
  },
  {
    id: 'monas',
    name: "Mona's",
    neighborhood: 'East Village',
    address: '224 Avenue B',
    lat: 40.7291774,
    lng: -73.9784775,
    priceTier: 1,
    tags: ['dive', 'locals', 'old-nyc', 'cheap', 'rough'],
    blurb: 'Avenue B dive that never quit. Late, cheap, and gloriously dim.',
    lastVerified: INGESTED,
  },

  // ---------- West Village ----------
  {
    id: 'stonewall-inn',
    name: 'Stonewall Inn',
    neighborhood: 'West Village',
    address: '53 Christopher St',
    lat: 40.7338379,
    lng: -74.0021637,
    priceTier: 2,
    tags: ['old-nyc', 'locals', 'buzzy', 'live', 'mid'],
    blurb: 'The birthplace of Pride. A living landmark that still pours a stiff one.',
    lastVerified: INGESTED,
  },
  {
    id: 'julius',
    name: "Julius'",
    neighborhood: 'West Village',
    address: '159 W 10th St',
    lat: 40.7345357,
    lng: -74.00163,
    priceTier: 1,
    tags: ['old-nyc', 'pub', 'locals', 'dive', 'cheap'],
    blurb: "NYC's oldest gay bar. Wood-paneled, beloved, famous for a griddle burger.",
    lastVerified: INGESTED,
  },
  {
    id: 'arthurs-tavern',
    name: "Arthur's Tavern",
    neighborhood: 'West Village',
    address: '57 Grove St',
    lat: 40.7332008,
    lng: -74.0034514,
    priceTier: 1,
    tags: ['jazz', 'live', 'old-nyc', 'locals', 'cheap'],
    blurb: 'Live jazz and blues since 1937. Cramped, loud, perfect.',
    lastVerified: INGESTED,
  },
  {
    id: 'blind-tiger',
    name: 'Blind Tiger',
    neighborhood: 'West Village',
    address: '281 Bleecker St',
    lat: 40.7318556,
    lng: -74.0032442,
    priceTier: 2,
    tags: ['beer', 'pub', 'buzzy', 'locals', 'mid'],
    blurb: 'Craft-beer mecca. Rare taps, cask ales, and a serious cheese plate.',
    lastVerified: INGESTED,
  },
  {
    id: 'katana-kitten',
    name: 'Katana Kitten',
    neighborhood: 'West Village',
    address: '531 Hudson St',
    lat: 40.7342475,
    lng: -74.0064498,
    priceTier: 3,
    tags: ['cocktail', 'trendy', 'industry', 'polished', 'pricey'],
    blurb: 'Japanese-American cocktail bar on every "world\'s best" list. Highballs done right.',
    lastVerified: INGESTED,
  },

  // ---------- Chelsea ----------
  {
    id: 'jungle-bird',
    name: 'Jungle Bird',
    neighborhood: 'Chelsea',
    address: '174 8th Ave',
    lat: 40.7425561,
    lng: -74.0000871,
    priceTier: 2,
    tags: ['cocktail', 'trendy', 'buzzy', 'date', 'mid'],
    blurb: 'Tropical tiki den. Frozen drinks, big flavors, no passport required.',
    lastVerified: INGESTED,
  },
  {
    id: 'sid-golds',
    name: "Sid Gold's Request Room",
    neighborhood: 'Chelsea',
    address: '165 W 26th St',
    lat: 40.7459514,
    lng: -73.9935846,
    priceTier: 2,
    tags: ['lounge', 'live', 'buzzy', 'trendy', 'mid'],
    blurb: 'Live-piano request room. Belt a show tune — the pianist already knows it.',
    lastVerified: INGESTED,
  },
  {
    id: 'gallow-green',
    name: 'Gallow Green',
    neighborhood: 'Chelsea',
    address: '542 W 27th St',
    lat: 40.7507231,
    lng: -74.0041431,
    priceTier: 3,
    tags: ['rooftop', 'garden', 'romantic', 'date', 'instagrammable'],
    blurb: "Sleep No More's rooftop garden. String lights, a railcar bar, pure theater.",
    lastVerified: INGESTED,
  },
  {
    id: 'american-whiskey',
    name: 'American Whiskey',
    neighborhood: 'Chelsea',
    address: '247 W 30th St',
    lat: 40.7493745,
    lng: -73.9940709,
    priceTier: 2,
    tags: ['cocktail', 'lounge', 'post-work', 'beer', 'mid'],
    blurb: 'Hundreds of whiskeys over three levels. Come thirsty, leave educated.',
    lastVerified: INGESTED,
  },
  {
    id: 'tir-na-nog',
    name: 'Tír na nÓg',
    neighborhood: 'Chelsea',
    address: '315 W 39th St',
    lat: 40.7559521,
    lng: -73.9920605,
    priceTier: 2,
    tags: ['pub', 'beer', 'post-work', 'buzzy', 'mid'],
    blurb: 'Pre-game Irish pub by Penn Station. Loud, packed, jerseys everywhere.',
    lastVerified: INGESTED,
  },

  // ---------- Midtown ----------
  {
    id: 'birdland',
    name: 'Birdland Jazz Club',
    neighborhood: 'Midtown',
    address: '315 W 44th St',
    lat: 40.7590853,
    lng: -73.9896379,
    priceTier: 3,
    tags: ['jazz', 'live', 'old-nyc', 'date', 'pricey'],
    blurb: 'Jazz institution named for Charlie Parker. Two sets a night, every night.',
    lastVerified: INGESTED,
  },
  {
    id: 'magic-hour',
    name: 'Magic Hour Rooftop',
    neighborhood: 'Midtown',
    address: '485 7th Ave',
    lat: 40.7524,
    lng: -73.9893,
    priceTier: 4,
    tags: ['rooftop', 'instagrammable', 'trendy', 'buzzy', 'splurge'],
    blurb: 'Whimsical rooftop with a carousel and topiary. Skyline views, frozen rosé.',
    lastVerified: INGESTED,
  },
  {
    id: 'the-skylark',
    name: 'The Skylark',
    neighborhood: 'Midtown',
    address: '200 W 39th St',
    lat: 40.7542367,
    lng: -73.9889033,
    priceTier: 3,
    tags: ['rooftop', 'cocktail', 'polished', 'date', 'pricey'],
    blurb: '30th-floor cocktail lounge above the theater district. Dress the part.',
    lastVerified: INGESTED,
  },
  {
    id: 'bar-54',
    name: 'Bar 54',
    neighborhood: 'Midtown',
    address: '135 W 45th St',
    lat: 40.757572,
    lng: -73.9840223,
    priceTier: 4,
    tags: ['rooftop', 'instagrammable', 'splurge', 'buzzy', 'loud'],
    blurb: "NYC's highest rooftop bar, 54 floors over Times Square. Go for the view.",
    lastVerified: INGESTED,
  },
  {
    id: 'beer-authority',
    name: 'Beer Authority',
    neighborhood: 'Midtown',
    address: '300 W 40th St',
    lat: 40.7559874,
    lng: -73.9910754,
    priceTier: 2,
    tags: ['beer', 'pub', 'buzzy', 'tourist', 'mid'],
    blurb: 'Multi-level beer hall by Port Authority. 90 taps and a rooftop.',
    lastVerified: INGESTED,
  },

  // ---------- FiDi ----------
  {
    id: 'manhatta',
    name: 'Manhatta',
    neighborhood: 'FiDi',
    address: '28 Liberty St, 60th fl',
    lat: 40.7078,
    lng: -74.0087,
    priceTier: 4,
    tags: ['cocktail', 'rooftop', 'polished', 'date', 'splurge'],
    blurb: '60 floors up. Floor-to-ceiling harbor views and a serious cocktail list.',
    lastVerified: INGESTED,
  },
  {
    id: 'overstory',
    name: 'Overstory',
    neighborhood: 'FiDi',
    address: '70 Pine St, 64th fl',
    lat: 40.7066,
    lng: -74.0081,
    priceTier: 4,
    tags: ['cocktail', 'rooftop', 'polished', 'date', 'splurge'],
    blurb: 'World-ranked rooftop cocktails above the canyon of FiDi. Reserve ahead.',
    lastVerified: INGESTED,
  },
  {
    id: 'clinton-hall',
    name: 'Clinton Hall',
    neighborhood: 'FiDi',
    address: '90 Washington St',
    lat: 40.7080405,
    lng: -74.014882,
    priceTier: 2,
    tags: ['beer', 'buzzy', 'post-work', 'pub', 'mid'],
    blurb: 'Beer hall with 20+ craft taps, picnic tables, and Jenga. Banker happy hour.',
    lastVerified: INGESTED,
  },
  {
    id: 'jeremys-ale-house',
    name: "Jeremy's Ale House",
    neighborhood: 'FiDi',
    address: '228 Front St',
    lat: 40.707725,
    lng: -74.0021054,
    priceTier: 1,
    tags: ['dive', 'old-nyc', 'cheap', 'locals', 'beer'],
    blurb: 'Styrofoam quarts of beer and bras on the ceiling. A Seaport relic.',
    lastVerified: INGESTED,
  },

  // ---------- UWS ----------
  {
    id: 'dublin-house',
    name: 'Dublin House',
    neighborhood: 'UWS',
    address: '225 W 79th St',
    lat: 40.7838465,
    lng: -73.9792285,
    priceTier: 1,
    tags: ['pub', 'old-nyc', 'locals', 'cheap', 'beer'],
    blurb: '1933 neon harp out front, regulars within. The platonic UWS Irish pub.',
    lastVerified: INGESTED,
  },
  {
    id: 'dive-75',
    name: 'Dive 75',
    neighborhood: 'UWS',
    address: '101 W 75th St',
    lat: 40.7796024,
    lng: -73.9776732,
    priceTier: 1,
    tags: ['dive', 'locals', 'chill', 'cheap', 'indie'],
    blurb: 'Board games, fish tanks, and a no-attitude crowd. A dive in name and heart.',
    lastVerified: INGESTED,
  },
  {
    id: 'tiki-chick',
    name: 'Tiki Chick',
    neighborhood: 'UWS',
    address: '517 Amsterdam Ave',
    lat: 40.7868369,
    lng: -73.9753999,
    priceTier: 2,
    tags: ['cocktail', 'buzzy', 'trendy', 'date', 'mid'],
    blurb: 'Frozen painkillers and rum punches. A splash of the tropics on Amsterdam.',
    lastVerified: INGESTED,
  },
  {
    id: 'george-keeley',
    name: 'George Keeley',
    neighborhood: 'UWS',
    address: '485 Amsterdam Ave',
    lat: 40.7858366,
    lng: -73.9759863,
    priceTier: 2,
    tags: ['beer', 'pub', 'locals', 'chill', 'mid'],
    blurb: 'Rotating craft taps and a back room for serious beer talk.',
    lastVerified: INGESTED,
  },

  // ---------- UES ----------
  {
    id: 'jg-melon',
    name: 'J.G. Melon',
    neighborhood: 'UES',
    address: '1291 3rd Ave',
    lat: 40.771073,
    lng: -73.9593705,
    priceTier: 2,
    tags: ['pub', 'old-nyc', 'locals', 'post-work', 'mid'],
    blurb: "Checkered cloths, cottage fries, and the city's most argued-over burger.",
    lastVerified: INGESTED,
  },
  {
    id: 'pony-bar',
    name: 'The Pony Bar',
    neighborhood: 'UES',
    address: '1444 1st Ave',
    lat: 40.76977,
    lng: -73.954316,
    priceTier: 2,
    tags: ['beer', 'buzzy', 'post-work', 'locals', 'mid'],
    blurb: 'All-American craft taps on a chalkboard. When a keg kicks, a bell rings.',
    lastVerified: INGESTED,
  },
  {
    id: 'brandys-piano-bar',
    name: "Brandy's Piano Bar",
    neighborhood: 'UES',
    address: '235 E 84th St',
    lat: 40.7770447,
    lng: -73.9535563,
    priceTier: 2,
    tags: ['live', 'lounge', 'old-nyc', 'date', 'mid'],
    blurb: 'Singing-waiter piano bar. The staff belt Broadway between pouring rounds.',
    lastVerified: INGESTED,
  },
  {
    id: 'jones-wood-foundry',
    name: 'Jones Wood Foundry',
    neighborhood: 'UES',
    address: '401 E 76th St',
    lat: 40.7703398,
    lng: -73.9535872,
    priceTier: 2,
    tags: ['pub', 'garden', 'chill', 'date', 'mid'],
    blurb: 'English pub with a hidden back garden. Fish and chips, cask ale, calm.',
    lastVerified: INGESTED,
  },

  // ---------- Williamsburg ----------
  {
    id: 'barcade',
    name: 'Barcade',
    neighborhood: 'Williamsburg',
    address: '388 Union Ave',
    lat: 40.7120257,
    lng: -73.951117,
    priceTier: 2,
    tags: ['beer', 'indie', 'buzzy', 'locals', 'mid'],
    blurb: 'Classic arcade cabinets and a wall of craft taps. Quarters and IPAs.',
    lastVerified: INGESTED,
  },
  {
    id: 'union-pool',
    name: 'Union Pool',
    neighborhood: 'Williamsburg',
    address: '484 Union Ave',
    lat: 40.7150021,
    lng: -73.9516171,
    priceTier: 2,
    tags: ['dive', 'indie', 'buzzy', 'locals', 'garden'],
    blurb: 'Taco truck, photo booth, fire pit, and a singles-scene reputation. A rite.',
    lastVerified: INGESTED,
  },
  {
    id: 'skinny-dennis',
    name: 'Skinny Dennis',
    neighborhood: 'Williamsburg',
    address: '152 Metropolitan Ave',
    lat: 40.7158872,
    lng: -73.9621335,
    priceTier: 1,
    tags: ['dive', 'live', 'indie', 'cheap', 'locals'],
    blurb: 'Honky-tonk on Metropolitan. Free country music, frozen bourbon-and-coffee.',
    lastVerified: INGESTED,
  },
  {
    id: 'four-horsemen',
    name: 'The Four Horsemen',
    neighborhood: 'Williamsburg',
    address: '295 Grand St',
    lat: 40.7131594,
    lng: -73.9572441,
    priceTier: 3,
    tags: ['wine', 'polished', 'date', 'trendy', 'pricey'],
    blurb: "James Murphy's natural-wine bar. Michelin-listed plates, immaculate sound.",
    lastVerified: INGESTED,
  },
  {
    id: 'hotel-delmano',
    name: 'Hotel Delmano',
    neighborhood: 'Williamsburg',
    address: '82 Berry St',
    lat: 40.7197084,
    lng: -73.9580192,
    priceTier: 3,
    tags: ['cocktail', 'speakeasy', 'date', 'romantic', 'pricey'],
    blurb: "No sign, marble bar, antique mirrors. Williamsburg's most romantic room.",
    lastVerified: INGESTED,
  },
  {
    id: 'westlight',
    name: 'Westlight',
    neighborhood: 'Williamsburg',
    address: '111 N 12th St, 22nd fl',
    lat: 40.7223,
    lng: -73.9568,
    priceTier: 4,
    tags: ['rooftop', 'cocktail', 'instagrammable', 'date', 'splurge'],
    blurb: '22nd-floor rooftop at The William Vale. Skyline-for-days, global small plates.',
    lastVerified: INGESTED,
  },
  {
    id: 'brooklyn-bowl',
    name: 'Brooklyn Bowl',
    neighborhood: 'Williamsburg',
    address: '61 Wythe Ave',
    lat: 40.7220528,
    lng: -73.9575486,
    priceTier: 2,
    tags: ['live', 'buzzy', 'loud', 'indie', 'mid'],
    blurb: 'Bowling, live bands, and Blue Ribbon fried chicken under one giant roof.',
    lastVerified: INGESTED,
  },

  // ---------- Greenpoint ----------
  {
    id: 'achilles-heel',
    name: 'Achilles Heel',
    neighborhood: 'Greenpoint',
    address: '180 West St',
    lat: 40.7332,
    lng: -73.9597,
    priceTier: 2,
    tags: ['cocktail', 'chill', 'date', 'polished', 'mid'],
    blurb: 'Corner tavern by the water. Daylight cocktails, candlelit dinners, perfect light.',
    lastVerified: INGESTED,
  },
  {
    id: 'torst',
    name: 'Tørst',
    neighborhood: 'Greenpoint',
    address: '615 Manhattan Ave',
    lat: 40.7233997,
    lng: -73.9508189,
    priceTier: 3,
    tags: ['beer', 'polished', 'chill', 'trendy', 'pricey'],
    blurb: 'Minimalist Danish beer bar. 21 brass taps of the rare and the wild.',
    lastVerified: INGESTED,
  },
  {
    id: 'black-rabbit',
    name: 'Black Rabbit',
    neighborhood: 'Greenpoint',
    address: '91 Greenpoint Ave',
    lat: 40.7301692,
    lng: -73.9566347,
    priceTier: 2,
    tags: ['pub', 'old-nyc', 'locals', 'chill', 'mid'],
    blurb: 'Tin ceilings, a fireplace, free Sunday bingo. A Greenpoint living room.',
    lastVerified: INGESTED,
  },
  {
    id: 'saint-vitus-bar',
    name: 'Saint Vitus',
    neighborhood: 'Greenpoint',
    address: '1120 Manhattan Ave',
    lat: 40.7367784,
    lng: -73.9551724,
    priceTier: 1,
    tags: ['live', 'loud', 'indie', 'locals', 'cheap'],
    blurb: 'Black-clad metal venue and bar. Loud shows, cheap shots, devil horns up.',
    lastVerified: INGESTED,
  },
  {
    id: 'sunshine-laundromat',
    name: 'Sunshine Laundromat',
    neighborhood: 'Greenpoint',
    address: '860 Manhattan Ave',
    lat: 40.7293024,
    lng: -73.9536252,
    priceTier: 1,
    tags: ['dive', 'indie', 'buzzy', 'chill', 'cheap'],
    blurb: 'A working laundromat up front; a pinball speakeasy through the back wall.',
    lastVerified: INGESTED,
  },
  {
    id: 'pencil-factory',
    name: 'The Pencil Factory',
    neighborhood: 'Greenpoint',
    address: '142 Franklin St',
    lat: 40.7297697,
    lng: -73.9574356,
    priceTier: 2,
    tags: ['pub', 'locals', 'chill', 'beer', 'mid'],
    blurb: 'Corner bar in an old Eberhard Faber building. Wobbly stools, easy regulars.',
    lastVerified: INGESTED,
  },
  {
    id: 'threes-brewing-gp',
    name: 'Threes Brewing',
    neighborhood: 'Greenpoint',
    address: '113 Franklin St',
    lat: 40.7302402,
    lng: -73.9578047,
    priceTier: 2,
    tags: ['beer', 'garden', 'buzzy', 'indie', 'mid'],
    blurb: 'Brewery taproom with rotating food pop-ups and a big back room.',
    lastVerified: INGESTED,
  },

  // ---------- Bushwick ----------
  {
    id: 'mood-ring',
    name: 'Mood Ring',
    neighborhood: 'Bushwick',
    address: '1260 Myrtle Ave',
    lat: 40.6977941,
    lng: -73.9269769,
    priceTier: 2,
    tags: ['cocktail', 'dance', 'trendy', 'buzzy', 'indie'],
    blurb: 'Astrology-themed bar with zodiac cocktails and a neon dance floor.',
    lastVerified: INGESTED,
  },
  {
    id: 'alphaville',
    name: 'Alphaville',
    neighborhood: 'Bushwick',
    address: '140 Wilson Ave',
    lat: 40.7005289,
    lng: -73.9258157,
    priceTier: 1,
    tags: ['live', 'dance', 'indie', 'loud', 'cheap'],
    blurb: 'Front bar, back venue. DJs, bands, and a young Bushwick crowd.',
    lastVerified: INGESTED,
  },
  {
    id: 'happyfun-hideaway',
    name: 'Happyfun Hideaway',
    neighborhood: 'Bushwick',
    address: '1211 Myrtle Ave',
    lat: 40.6975483,
    lng: -73.9316464,
    priceTier: 1,
    tags: ['dive', 'dance', 'garden', 'buzzy', 'cheap'],
    blurb: 'Day-glo dive with a back patio and a no-rules dance floor.',
    lastVerified: INGESTED,
  },
  {
    id: 'wonderville',
    name: 'Wonderville',
    neighborhood: 'Bushwick',
    address: '1186 Broadway',
    lat: 40.6924,
    lng: -73.9275,
    priceTier: 1,
    tags: ['indie', 'buzzy', 'beer', 'dance', 'cheap'],
    blurb: 'A bar full of homemade arcade games. Part dive, part art project, all fun.',
    lastVerified: INGESTED,
  },
  {
    id: 'ornithology-jazz-club',
    name: 'Ornithology Jazz Club',
    neighborhood: 'Bushwick',
    address: '6 Suydam St',
    lat: 40.6955322,
    lng: -73.9320225,
    priceTier: 1,
    tags: ['jazz', 'live', 'lounge', 'date', 'cheap'],
    blurb: 'Intimate Bushwick jazz room. Donation-based sets, serious players.',
    lastVerified: INGESTED,
  },
  {
    id: 'bootleg-bar',
    name: 'Bootleg Bar',
    neighborhood: 'Bushwick',
    address: '113 Cooper St',
    lat: 40.6988,
    lng: -73.9172,
    priceTier: 2,
    tags: ['cocktail', 'lounge', 'chill', 'date', 'garden'],
    blurb: 'Tiki-leaning cocktails and a backyard. A grown-up corner of Bushwick.',
    lastVerified: INGESTED,
  },
  {
    id: 'gotham-city-lounge',
    name: 'Gotham City Lounge',
    neighborhood: 'Bushwick',
    address: '1293 Myrtle Ave',
    lat: 40.6980784,
    lng: -73.9266193,
    priceTier: 1,
    tags: ['dive', 'indie', 'cheap', 'locals', 'rough'],
    blurb: 'Comic-book dive plastered floor-to-ceiling. Cheap, weird, beloved.',
    lastVerified: INGESTED,
  },

  // ---------- Park Slope ----------
  {
    id: 'barbes',
    name: 'Barbès',
    neighborhood: 'Park Slope',
    address: '376 9th St',
    lat: 40.6677432,
    lng: -73.9838847,
    priceTier: 2,
    tags: ['live', 'jazz', 'indie', 'chill', 'mid'],
    blurb: 'Back-room world music nightly — Slavic brass, Brazilian, jazz. Tip the band.',
    lastVerified: INGESTED,
  },
  {
    id: 'royal-palms-shuffleboard',
    name: 'Royal Palms Shuffleboard Club',
    neighborhood: 'Park Slope',
    address: '514 Union St',
    lat: 40.6787406,
    lng: -73.9868491,
    priceTier: 2,
    tags: ['buzzy', 'trendy', 'date', 'garden', 'mid'],
    blurb: 'Ten shuffleboard courts, food trucks, frozen drinks. Game-night central.',
    lastVerified: INGESTED,
  },
  {
    id: 'gingers-bar',
    name: "Ginger's Bar",
    neighborhood: 'Park Slope',
    address: '363 5th Ave',
    lat: 40.6712936,
    lng: -73.9842242,
    priceTier: 1,
    tags: ['locals', 'chill', 'beer', 'dive', 'cheap'],
    blurb: "Park Slope's beloved lesbian bar. Pool table, back garden, warm regulars.",
    lastVerified: INGESTED,
  },
  {
    id: 'high-dive',
    name: 'High Dive',
    neighborhood: 'Park Slope',
    address: '243 5th Ave',
    lat: 40.6749021,
    lng: -73.981197,
    priceTier: 1,
    tags: ['dive', 'locals', 'cheap', 'chill', 'beer'],
    blurb: 'Exactly what it says. Cheap drafts, a good jukebox, easy nights.',
    lastVerified: INGESTED,
  },
  {
    id: 'owl-farm',
    name: 'The Owl Farm',
    neighborhood: 'Park Slope',
    address: '297 9th St',
    lat: 40.6696503,
    lng: -73.986567,
    priceTier: 2,
    tags: ['beer', 'chill', 'locals', 'post-work', 'mid'],
    blurb: 'Two dozen rotating taps and a chalkboard menu. A Slope beer hang.',
    lastVerified: INGESTED,
  },
  {
    id: 'dram-shop',
    name: 'Dram Shop',
    neighborhood: 'Park Slope',
    address: '339 9th St',
    lat: 40.668841,
    lng: -73.9850758,
    priceTier: 2,
    tags: ['pub', 'beer', 'locals', 'buzzy', 'mid'],
    blurb: "Upstairs pool tables, good burgers, lots of taps. The neighborhood's rec room.",
    lastVerified: INGESTED,
  },
];
