import type { Bar } from '@/types';

// Catalog EXPANSION pass 2 (2026-07-22) — young-crowd (20-35) skew. Bars sourced
// from web research (Reddit r/AskNYC/r/nyc, The Infatuation, Eater, Time Out,
// Thrillist via Perplexity), structured by a parallel per-neighborhood fan-out
// GROUNDED on the real street addresses from those sources, then adversarially
// reviewed and deduped against the full existing catalog.
//
// IMPORTANT: same R4 status as coreBars/extraBars/expansionBars — lastVerified
// is a PLACEHOLDER and coords are best-effort from the sourced addresses, NOT
// personally verified. Verify (or Places-API pull) before public factual claims.

export const expansion2Bars: Bar[] = [
  { id: 'birdys', name: 'Birdys', neighborhood: 'Bushwick', address: '1215 Myrtle Ave, Brooklyn, NY', lat: 40.6976, lng: -73.9289, priceTier: 2, tags: ['wine', 'chill', 'date', 'trendy', 'indie'], blurb: 'Natural wine and cocktails in a cozy space.', lastVerified: '2026-04-01' },
  { id: 'bright-room', name: 'Bright Room', neighborhood: 'Bushwick', address: '1063 Broadway, Brooklyn, NY', lat: 40.6961, lng: -73.9258, priceTier: 2, tags: ['cocktail', 'chill', 'date', 'trendy', 'wine'], blurb: 'Airy cafe by day, cocktail bar by night.', lastVerified: '2026-04-01' },
  { id: 'elsewhere', name: 'Elsewhere', neighborhood: 'Bushwick', address: '599 Johnson Ave, Brooklyn, NY', lat: 40.7125, lng: -73.9234, priceTier: 3, tags: ['dance', 'live', 'rooftop', 'buzzy', 'house'], blurb: 'Multi-room music venue and club with popular rooftop.', lastVerified: '2026-04-01' },
  { id: 'house-of-yes', name: 'House of Yes', neighborhood: 'Bushwick', address: '2 Wyckoff Ave, Brooklyn, NY', lat: 40.7066, lng: -73.9227, priceTier: 3, tags: ['dance', 'buzzy', 'cocktail', 'instagrammable', 'loud'], blurb: 'Circus-themed nightclub with wild themed parties and performances.', lastVerified: '2026-04-01' },
  { id: 'left-hand-path', name: 'Left Hand Path', neighborhood: 'Bushwick', address: '89 Wyckoff Ave, Brooklyn, NY', lat: 40.7038, lng: -73.9198, priceTier: 2, tags: ['cocktail', 'chill', 'date', 'lounge', 'trendy'], blurb: 'Intimate cocktail bar with inventive seasonal drinks.', lastVerified: '2026-04-01' },
  { id: 'the-johnsons', name: 'The Johnsons', neighborhood: 'Bushwick', address: '369 Troutman St, Brooklyn, NY', lat: 40.7058, lng: -73.9233, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'chill', 'old-nyc'], blurb: 'Beloved cheap dive with pool table and jukebox.', lastVerified: '2026-04-01' },
  { id: 'three-diamond-door', name: 'Three Diamond Door', neighborhood: 'Bushwick', address: '211 Knickerbocker Ave, Brooklyn, NY', lat: 40.7048, lng: -73.9208, priceTier: 2, tags: ['cocktail', 'garden', 'chill', 'date', 'trendy'], blurb: 'Stylish cocktail bar with a spacious back garden.', lastVerified: '2026-04-01' },
  { id: 'coppelia-bar', name: 'Coppelia Bar', neighborhood: 'Chelsea', address: '207 W 14th St, New York, NY', lat: 40.7392, lng: -74.001, priceTier: 2, tags: ['cocktail', 'chill', 'locals', 'buzzy'], blurb: '24-hour Latin diner with a full cocktail bar.', lastVerified: '2026-04-01' },
  { id: 'porchlight', name: 'Porchlight', neighborhood: 'Chelsea', address: '271 11th Ave, New York, NY', lat: 40.7508, lng: -74.0038, priceTier: 3, tags: ['cocktail', 'buzzy', 'post-work', 'lounge', 'date'], blurb: 'Danny Meyer\'s lively cocktail bar on far West Chelsea.', lastVerified: '2026-04-01' },
  { id: 'raines-law-room', name: 'Raines Law Room', neighborhood: 'Chelsea', address: '48 W 17th St, New York, NY', lat: 40.7385, lng: -73.993, priceTier: 3, tags: ['speakeasy', 'cocktail', 'date', 'romantic', 'old-nyc'], blurb: 'Plush buzzer-entry speakeasy pouring expert craft cocktails.', lastVerified: '2026-04-01' },
  { id: 'bibi-wine-bar', name: 'Bibi Wine Bar', neighborhood: 'East Village', address: '211 E 4th St, New York, NY', lat: 40.7246, lng: -73.9825, priceTier: 3, tags: ['wine', 'date', 'chill', 'romantic', 'indie'], blurb: 'Snug natural-wine spot for low-key East Village dates.', lastVerified: '2026-04-01' },
  { id: 'joyface', name: 'Joyface', neighborhood: 'East Village', address: '104 Avenue C, New York, NY', lat: 40.7244, lng: -73.9757, priceTier: 2, tags: ['cocktail', 'buzzy', 'date', 'trendy', 'loud'], blurb: 'Disco-lit Alphabet City cocktails with a party pulse.', lastVerified: '2026-04-01' },
  { id: 'ruffian', name: 'Ruffian', neighborhood: 'East Village', address: '125 E 7th St, New York, NY', lat: 40.7255, lng: -73.9844, priceTier: 3, tags: ['wine', 'date', 'chill', 'romantic', 'polished'], blurb: 'Intimate natural-wine bar with global small plates.', lastVerified: '2026-04-01' },
  { id: 'smithereens', name: 'Smithereens', neighborhood: 'East Village', address: '414 E 9th St, New York, NY', lat: 40.7287, lng: -73.9848, priceTier: 3, tags: ['cocktail', 'date', 'chill', 'romantic', 'trendy'], blurb: 'Intimate cocktail den with seasonal, produce-driven drinks.', lastVerified: '2026-04-01' },
  { id: 'the-ready-rooftop-bar', name: 'The Ready Rooftop Bar', neighborhood: 'East Village', address: '112 E 11th St, New York, NY', lat: 40.7319, lng: -73.9894, priceTier: 3, tags: ['rooftop', 'cocktail', 'buzzy', 'tourist', 'instagrammable'], blurb: 'Moxy hotel rooftop with skyline views and cocktails.', lastVerified: '2026-04-01' },
  { id: 'crown-shy-bar', name: 'Crown Shy Bar', neighborhood: 'FiDi', address: '70 Pine St, New York, NY', lat: 40.7058, lng: -74.0073, priceTier: 3, tags: ['cocktail', 'date', 'polished', 'post-work', 'buzzy'], blurb: 'Sleek cocktails inside a landmark art deco tower.', lastVerified: '2026-04-01' },
  { id: 'underdog', name: 'Underdog', neighborhood: 'FiDi', address: '55 Stone St, New York, NY', lat: 40.7041, lng: -74.0112, priceTier: 2, tags: ['wine', 'post-work', 'chill', 'date', 'buzzy'], blurb: 'Natural wine bar on historic cobblestoned Stone Street.', lastVerified: '2026-04-01' },
  { id: 'goldies', name: 'Goldies', neighborhood: 'Greenpoint', address: '195 Nassau Ave, Brooklyn, NY', lat: 40.7241, lng: -73.9458, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'buzzy'], blurb: 'Unpretentious Nassau Ave dive with cheap pours and locals.', lastVerified: '2026-04-01' },
  { id: 'oak-and-iron', name: 'Oak and Iron', neighborhood: 'Greenpoint', address: '147 Franklin St, Brooklyn, NY', lat: 40.73, lng: -73.9578, priceTier: 3, tags: ['cocktail', 'date', 'chill', 'romantic'], blurb: 'Intimate cocktail spot on Franklin, dialed for date night.', lastVerified: '2026-04-01' },
  { id: 'troost', name: 'Troost', neighborhood: 'Greenpoint', address: '1011 Manhattan Ave, Brooklyn, NY', lat: 40.7327, lng: -73.9546, priceTier: 3, tags: ['cocktail', 'chill', 'date', 'romantic', 'locals'], blurb: 'Dark, candlelit cocktail bar beloved for cozy dates.', lastVerified: '2026-04-01' },
  { id: 'casa-mezcal', name: 'Casa Mezcal', neighborhood: 'LES', address: '86 Orchard St, New York, NY', lat: 40.7172, lng: -73.9903, priceTier: 2, tags: ['cocktail', 'buzzy', 'date', 'loud', 'locals'], blurb: 'Mezcal-focused Mexican bar with agave flights.', lastVerified: '2026-04-01' },
  { id: 'kind-regards', name: 'Kind Regards', neighborhood: 'LES', address: '152 Ludlow St, New York, NY', lat: 40.7215, lng: -73.9862, priceTier: 3, tags: ['cocktail', 'lounge', 'date', 'polished', 'trendy'], blurb: 'Japanese-inspired cocktails in a sleek date-night room.', lastVerified: '2026-04-01' },
  { id: 'la-contenta', name: 'La Contenta', neighborhood: 'LES', address: '102 Norfolk St, New York, NY', lat: 40.7195, lng: -73.9852, priceTier: 2, tags: ['cocktail', 'buzzy', 'date', 'loud', 'locals'], blurb: 'Mezcal margaritas and Mexican plates, lively crowd.', lastVerified: '2026-04-01' },
  { id: 'las-lap', name: 'Las Lap', neighborhood: 'LES', address: '74 Orchard St, New York, NY', lat: 40.7168, lng: -73.9905, priceTier: 2, tags: ['cocktail', 'chill', 'buzzy', 'date', 'indie'], blurb: 'Tiny Caribbean rum bar with island cocktails.', lastVerified: '2026-04-01' },
  { id: 'le-dive', name: 'Le Dive', neighborhood: 'LES', address: '37 Canal St, New York, NY', lat: 40.7143, lng: -73.9909, priceTier: 2, tags: ['wine', 'buzzy', 'trendy', 'date', 'indie'], blurb: 'Parisian-style corner wine bar, always packed.', lastVerified: '2026-04-01' },
  { id: 'parcelle', name: 'Parcelle', neighborhood: 'LES', address: '135 Division St, New York, NY', lat: 40.7148, lng: -73.9906, priceTier: 3, tags: ['wine', 'chill', 'date', 'polished', 'trendy'], blurb: 'Wine bar and bottle shop with serious pours.', lastVerified: '2026-04-01' },
  { id: 'peoples-wine-bar', name: 'Peoples Wine Bar', neighborhood: 'LES', address: '115 Delancey St, New York, NY', lat: 40.7183, lng: -73.9878, priceTier: 2, tags: ['wine', 'chill', 'indie', 'buzzy', 'date'], blurb: 'Natural wine and snacks tucked in the Market Line.', lastVerified: '2026-04-01' },
  { id: 'skin-contact', name: 'Skin Contact', neighborhood: 'LES', address: '76 Orchard St, New York, NY', lat: 40.7169, lng: -73.9904, priceTier: 2, tags: ['wine', 'buzzy', 'loud', 'trendy', 'indie'], blurb: 'Natural wine bar that turns into a late-night party.', lastVerified: '2026-04-01' },
  { id: 'the-flower-shop', name: 'The Flower Shop', neighborhood: 'LES', address: '107 Eldridge St, New York, NY', lat: 40.7176, lng: -73.9924, priceTier: 3, tags: ['cocktail', 'buzzy', 'date', 'trendy', 'chill'], blurb: 'Buzzy retro bar-restaurant with a rowdy basement.', lastVerified: '2026-04-01' },
  { id: 'wildair', name: 'Wildair', neighborhood: 'LES', address: '142 Orchard St, New York, NY', lat: 40.7205, lng: -73.9888, priceTier: 3, tags: ['wine', 'date', 'polished', 'trendy', 'buzzy'], blurb: 'Natural wine and small plates, tight and lively.', lastVerified: '2026-04-01' },
  { id: '230-fifth-rooftop-bar', name: '230 Fifth Rooftop Bar', neighborhood: 'Midtown', address: '230 5th Ave, New York, NY', lat: 40.7443, lng: -73.988, priceTier: 3, tags: ['rooftop', 'buzzy', 'tourist', 'instagrammable', 'cocktail'], blurb: 'Sprawling rooftop with Empire State Building views.', lastVerified: '2026-04-01' },
  { id: 'bar-at-the-modern', name: 'Bar at The Modern', neighborhood: 'Midtown', address: '9 W 53rd St, New York, NY', lat: 40.7614, lng: -73.9772, priceTier: 4, tags: ['cocktail', 'polished', 'date', 'splurge', 'lounge'], blurb: 'Refined cocktails inside MoMA\'s acclaimed restaurant.', lastVerified: '2026-04-01' },
  { id: 'dear-irving-on-hudson', name: 'Dear Irving on Hudson', neighborhood: 'Midtown', address: '310 W 40th St, New York, NY', lat: 40.7564, lng: -73.993, priceTier: 3, tags: ['rooftop', 'cocktail', 'date', 'polished', 'instagrammable', 'buzzy'], blurb: 'Glam rooftop cocktails over Times Square.', lastVerified: '2026-04-01' },
  { id: 'haswell-greens', name: 'Haswell Greens', neighborhood: 'Midtown', address: '240 W 52nd St, New York, NY', lat: 40.7636, lng: -73.9855, priceTier: 2, tags: ['pub', 'beer', 'post-work', 'buzzy', 'locals'], blurb: 'Roomy Midtown sports pub for post-work pints.', lastVerified: '2026-04-01' },
  { id: 'monarch-rooftop', name: 'Monarch Rooftop', neighborhood: 'Midtown', address: '71 W 35th St, New York, NY', lat: 40.7501, lng: -73.9855, priceTier: 3, tags: ['rooftop', 'buzzy', 'cocktail', 'instagrammable', 'date'], blurb: 'Buzzy Herald Square rooftop near the Empire State.', lastVerified: '2026-04-01' },
  { id: 'valerie', name: 'Valerie', neighborhood: 'Midtown', address: '45 W 45th St, New York, NY', lat: 40.7563, lng: -73.9818, priceTier: 3, tags: ['cocktail', 'romantic', 'date', 'polished', 'old-nyc'], blurb: 'Art-deco cocktail lounge with old-nyc glamour.', lastVerified: '2026-04-01' },
  { id: 'blueprint', name: 'Blueprint', neighborhood: 'Park Slope', address: '196 5th Ave, Brooklyn, NY', lat: 40.6787, lng: -73.9826, priceTier: 3, tags: ['cocktail', 'date', 'chill', 'locals'], blurb: 'Intimate craft cocktail bar and longtime date-night staple.', lastVerified: '2026-04-01' },
  { id: 'good-judy', name: 'Good Judy', neighborhood: 'Park Slope', address: '563 5th Ave, Brooklyn, NY', lat: 40.6636, lng: -73.9903, priceTier: 2, tags: ['dance', 'buzzy', 'cocktail', 'loud'], blurb: 'Lively LGBTQ+ bar with drag, dancing, and cocktails.', lastVerified: '2026-04-01' },
  { id: 'young-ethels', name: 'Young Ethels', neighborhood: 'Park Slope', address: '506 5th Ave, Brooklyn, NY', lat: 40.6664, lng: -73.9888, priceTier: 2, tags: ['cocktail', 'buzzy', 'date', 'locals'], blurb: 'Two-floor cocktail bar with upstairs games and buzz.', lastVerified: '2026-04-01' },
  { id: 'bondurants', name: 'Bondurants', neighborhood: 'UES', address: '303 E 85th St, New York, NY', lat: 40.7779, lng: -73.9513, priceTier: 3, tags: ['cocktail', 'date', 'buzzy', 'polished', 'post-work'], blurb: 'Bourbon-focused cocktail bar, buzzy and date-friendly.', lastVerified: '2026-04-01' },
  { id: 'stumble-inn', name: 'Stumble Inn', neighborhood: 'UES', address: '1454 2nd Ave, New York, NY', lat: 40.7714, lng: -73.9562, priceTier: 1, tags: ['dive', 'beer', 'cheap', 'buzzy', 'loud'], blurb: 'Rowdy sports dive with cheap beer and wings.', lastVerified: '2026-04-01' },
  { id: 'the-supply-house', name: 'The Supply House', neighborhood: 'UES', address: '1647 2nd Ave, New York, NY', lat: 40.7776, lng: -73.9512, priceTier: 2, tags: ['cocktail', 'lounge', 'date', 'chill', 'romantic'], blurb: 'Intimate, dimly-lit cocktail lounge for dates.', lastVerified: '2026-04-01' },
  { id: 'gebhards-beer-culture', name: 'Gebhards Beer Culture', neighborhood: 'UWS', address: '228 W 72nd St, New York, NY', lat: 40.7785, lng: -73.9825, priceTier: 2, tags: ['beer', 'pub', 'chill', 'post-work', 'date'], blurb: 'German-leaning craft beer bar with deep taps.', lastVerified: '2026-04-01' },
  { id: 'jakes-dilemma', name: 'Jakes Dilemma', neighborhood: 'UWS', address: '430 Amsterdam Ave, New York, NY', lat: 40.7853, lng: -73.976, priceTier: 2, tags: ['dive', 'beer', 'buzzy', 'loud', 'cheap'], blurb: 'Rowdy UWS sports dive with beer pong and cheap pours.', lastVerified: '2026-04-01' },
  { id: 'lions-head-tavern', name: 'Lions Head Tavern', neighborhood: 'UWS', address: '995 Amsterdam Ave, New York, NY', lat: 40.8028, lng: -73.9662, priceTier: 2, tags: ['beer', 'locals', 'chill', 'pub', 'cheap'], blurb: 'Easygoing uptown neighborhood pub with cheap beer and regulars.', lastVerified: '2026-04-01' },
  { id: 'art-bar', name: 'Art Bar', neighborhood: 'West Village', address: '52 8th Ave, New York, NY', lat: 40.7386, lng: -74.0026, priceTier: 2, tags: ['cocktail', 'lounge', 'chill', 'date', 'locals'], blurb: 'Dim neighborhood haunt with murals and a back-room fireplace.', lastVerified: '2026-04-01' },
  { id: 'dante-west-village', name: 'Dante West Village', neighborhood: 'West Village', address: '551 Hudson St, New York, NY', lat: 40.7358, lng: -74.0062, priceTier: 3, tags: ['cocktail', 'buzzy', 'date', 'polished', 'trendy'], blurb: 'Award-winning negronis and aperitivo in a buzzy, polished setting.', lastVerified: '2026-04-01' },
  { id: 'st-jardim', name: 'St Jardim', neighborhood: 'West Village', address: '183 W 10th St, New York, NY', lat: 40.7338, lng: -74.003, priceTier: 3, tags: ['wine', 'date', 'romantic', 'trendy', 'chill'], blurb: 'Botanical natural-wine bar pouring seasonal small plates.', lastVerified: '2026-04-01' },
  { id: 'the-four-faced-liar', name: 'The Four-Faced Liar', neighborhood: 'West Village', address: '165 W 4th St, New York, NY', lat: 40.7328, lng: -74.0011, priceTier: 2, tags: ['pub', 'beer', 'locals', 'chill', 'cheap'], blurb: 'Cozy Irish pub with Guinness and easygoing charm.', lastVerified: '2026-04-01' },
  { id: 'the-garret', name: 'The Garret', neighborhood: 'West Village', address: '296 Bleecker St, New York, NY', lat: 40.7317, lng: -74.0036, priceTier: 3, tags: ['cocktail', 'speakeasy', 'chill', 'date'], blurb: 'Hidden cocktail bar tucked above a Bleecker Street Five Guys.', lastVerified: '2026-04-01' },
  { id: 'the-spaniard', name: 'The Spaniard', neighborhood: 'West Village', address: '190 W 4th St, New York, NY', lat: 40.7336, lng: -74.0018, priceTier: 3, tags: ['cocktail', 'pub', 'post-work', 'polished'], blurb: 'Handsome gastropub with deep whiskey list and craft cocktails.', lastVerified: '2026-04-01' },
  { id: 'berry-park', name: 'Berry Park', neighborhood: 'Williamsburg', address: '4 Berry St, Brooklyn, NY', lat: 40.722, lng: -73.9538, priceTier: 2, tags: ['beer', 'rooftop', 'loud', 'post-work', 'buzzy'], blurb: 'Sprawling beer hall with a rooftop bar.', lastVerified: '2026-04-01' },
  { id: 'fresh-kills-bar', name: 'Fresh Kills Bar', neighborhood: 'Williamsburg', address: '161 Grand St, Brooklyn, NY', lat: 40.7143, lng: -73.9617, priceTier: 3, tags: ['cocktail', 'date', 'polished', 'romantic'], blurb: 'Polished cocktail bar with romantic date-night vibes.', lastVerified: '2026-04-01' },
  { id: 'the-commodore', name: 'The Commodore', neighborhood: 'Williamsburg', address: '366 Metropolitan Ave, Brooklyn, NY', lat: 40.7129, lng: -73.9527, priceTier: 2, tags: ['cocktail', 'buzzy', 'date', 'trendy'], blurb: 'Tiki cocktails and fried chicken, always buzzing.', lastVerified: '2026-04-01' },
  { id: 'the-levee', name: 'The Levee', neighborhood: 'Williamsburg', address: '160 N 14th St, Brooklyn, NY', lat: 40.7212, lng: -73.9557, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'chill', 'beer'], blurb: 'Cheap dive with free cheese balls and PBR.', lastVerified: '2026-04-01' },
];
