import type { Bar } from '@/types';

// Catalog EXPANSION pass (2026-07-22). Added via parallel fan-out — one agent
// per neighborhood returned schema-validated real bars, then an adversarial
// review agent flagged hallucinated/duplicate/mis-tagged entries. Deduped
// against the full existing catalog.
//
// IMPORTANT: like coreBars/extraBars, lastVerified is a PLACEHOLDER and the
// coords + addresses are best-effort from model knowledge — NOT personally
// verified. Real per-bar verification (or a Places-API pull for exact coords)
// remains R4 and must happen before any public factual claim.

export const expansionBars: Bar[] = [
  { id: 'boobie-trap', name: 'Boobie Trap', neighborhood: 'Bushwick', address: '308 Bleecker St, Brooklyn, NY 11237', lat: 40.702, lng: -73.9182, priceTier: 1, tags: ['dive', 'cheap', 'buzzy', 'locals', 'loud'], blurb: 'Grimy, cheap, gloriously weird. Peak Bushwick dive.', lastVerified: '2026-04-01' },
  { id: 'our-wicked-lady', name: 'Our Wicked Lady', neighborhood: 'Bushwick', address: '153 Morgan Ave, Brooklyn, NY 11237', lat: 40.7078, lng: -73.9331, priceTier: 2, tags: ['rooftop', 'dance', 'live', 'buzzy', 'loud', 'house'], blurb: 'Rooftop garden and live music. Bushwick party institution.', lastVerified: '2026-04-01' },
  { id: 'pearls-social-and-billy-club', name: 'Pearl\'s Social & Billy Club', neighborhood: 'Bushwick', address: '40 St Nicholas Ave, Brooklyn, NY 11237', lat: 40.7056, lng: -73.9235, priceTier: 3, tags: ['cocktail', 'speakeasy', 'date', 'romantic', 'old-nyc'], blurb: 'Vintage speakeasy vibes. Dim, boozy, made for dates.', lastVerified: '2026-04-01' },
  { id: 'pine-box-rock-shop', name: 'Pine Box Rock Shop', neighborhood: 'Bushwick', address: '12 Grattan St, Brooklyn, NY 11206', lat: 40.706, lng: -73.9332, priceTier: 2, tags: ['beer', 'live', 'pub', 'buzzy', 'loud', 'indie'], blurb: 'Old paint factory turned rock bar. Bands and beer.', lastVerified: '2026-04-01' },
  { id: 'the-sampler', name: 'The Sampler', neighborhood: 'Bushwick', address: '250 Central Ave, Brooklyn, NY 11221', lat: 40.6994, lng: -73.9216, priceTier: 2, tags: ['beer', 'cocktail', 'chill', 'locals', 'indie'], blurb: 'Craft beer and cocktails. Low-key neighborhood staple.', lastVerified: '2026-04-01' },
  { id: 'gym-sportsbar', name: 'Gym Sportsbar', neighborhood: 'Chelsea', address: '167 8th Ave, New York, NY 10011', lat: 40.7434, lng: -73.9989, priceTier: 2, tags: ['beer', 'locals', 'chill', 'post-work', 'loud'], blurb: 'Chelsea\'s gay sports bar. Games on, easy crowd.', lastVerified: '2026-04-01' },
  { id: 'peter-mcmanus-cafe', name: 'Peter McManus Cafe', neighborhood: 'Chelsea', address: '152 7th Ave, New York, NY 10011', lat: 40.7414, lng: -73.9975, priceTier: 1, tags: ['dive', 'old-nyc', 'locals', 'cheap', 'beer'], blurb: 'Family-run since 1936. Untouched Irish dive with real regulars.', lastVerified: '2026-04-01' },
  { id: 'the-park', name: 'The Park', neighborhood: 'Chelsea', address: '118 10th Ave, New York, NY 10011', lat: 40.744, lng: -74.0053, priceTier: 3, tags: ['lounge', 'garden', 'date', 'polished', 'romantic'], blurb: 'Sprawling indoor-outdoor garden lounge. Bring a date.', lastVerified: '2026-04-01' },
  { id: 'trailer-park-lounge', name: 'Trailer Park Lounge', neighborhood: 'Chelsea', address: '271 W 23rd St, New York, NY 10011', lat: 40.7451, lng: -73.9993, priceTier: 2, tags: ['dive', 'buzzy', 'cheap', 'chill', 'loud'], blurb: 'Kitschy trailer-trash decor, strong margaritas, tater tots.', lastVerified: '2026-04-01' },
  { id: '2a', name: '2A', neighborhood: 'East Village', address: '25 Avenue A, New York, NY 10009', lat: 40.7234, lng: -73.9868, priceTier: 2, tags: ['dive', 'chill', 'locals', 'beer', 'lounge'], blurb: 'Corner dive. Grab an upstairs window over Avenue A.', lastVerified: '2026-04-01' },
  { id: 'mcsorleys-old-ale-house', name: 'McSorley\'s Old Ale House', neighborhood: 'East Village', address: '15 E 7th St, New York, NY 10003', lat: 40.7288, lng: -73.9897, priceTier: 1, tags: ['dive', 'pub', 'beer', 'old-nyc', 'tourist', 'cheap'], blurb: 'Two beers only, light or dark. Sawdust since 1854.', lastVerified: '2026-04-01' },
  { id: 'pouring-ribbons', name: 'Pouring Ribbons', neighborhood: 'East Village', address: '225 Avenue B, 2nd Fl, New York, NY 10009', lat: 40.7268, lng: -73.9787, priceTier: 3, tags: ['cocktail', 'polished', 'date', 'pricey', 'industry'], blurb: 'Serious cocktails, no attitude. Menu maps intensity.', lastVerified: '2026-04-01' },
  { id: 'sophies', name: 'Sophie\'s', neighborhood: 'East Village', address: '509 E 5th St, New York, NY 10009', lat: 40.7247, lng: -73.9829, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'beer', 'chill'], blurb: 'Cash-only dive. Jukebox, cheap beer, zero frills.', lastVerified: '2026-04-01' },
  { id: 'the-wayland', name: 'The Wayland', neighborhood: 'East Village', address: '700 E 9th St, New York, NY 10009', lat: 40.7256, lng: -73.9783, priceTier: 2, tags: ['cocktail', 'live', 'buzzy', 'indie', 'date'], blurb: 'Live music, mason-jar cocktails, Alphabet City buzz.', lastVerified: '2026-04-01' },
  { id: 'killarney-rose', name: 'Killarney Rose', neighborhood: 'FiDi', address: '127 Pearl St, New York, NY 10005', lat: 40.7049, lng: -74.00887, priceTier: 1, tags: ['dive', 'pub', 'cheap', 'locals', 'post-work'], blurb: 'Cheap pours, no pretense. Classic Wall Street dive.', lastVerified: '2026-04-01' },
  { id: 'stone-street-tavern', name: 'Stone Street Tavern', neighborhood: 'FiDi', address: '52 Stone St, New York, NY 10004', lat: 40.70419, lng: -74.01099, priceTier: 2, tags: ['pub', 'beer', 'buzzy', 'post-work', 'locals'], blurb: 'Cobblestone-street pints. Packed elbow-to-elbow after work.', lastVerified: '2026-04-01' },
  { id: 'vintry-wine-and-whiskey', name: 'Vintry Wine & Whiskey', neighborhood: 'FiDi', address: '57 Stone St, New York, NY 10004', lat: 40.70417, lng: -74.01083, priceTier: 3, tags: ['wine', 'cocktail', 'lounge', 'date', 'polished'], blurb: 'Hundreds of wines and whiskeys. Grown-up date spot.', lastVerified: '2026-04-01' },
  { id: 'watermark-bar', name: 'Watermark Bar', neighborhood: 'FiDi', address: '78 South St, Pier 15, New York, NY 10038', lat: 40.7052, lng: -74.0023, priceTier: 3, tags: ['rooftop', 'cocktail', 'buzzy', 'date', 'instagrammable'], blurb: 'Open-air pier lounge over the East River.', lastVerified: '2026-04-01' },
  { id: 'broken-land', name: 'Broken Land', neighborhood: 'Greenpoint', address: '105 Franklin St, Brooklyn, NY 11222', lat: 40.7291, lng: -73.9573, priceTier: 3, tags: ['cocktail', 'chill', 'date', 'indie', 'lounge'], blurb: 'Dim, mellow cocktail den. Solid drinks, no fuss.', lastVerified: '2026-04-01' },
  { id: 'no-fun', name: 'No Fun', neighborhood: 'Greenpoint', address: '161 Nassau Ave, Brooklyn, NY 11222', lat: 40.7243, lng: -73.949, priceTier: 2, tags: ['cocktail', 'buzzy', 'trendy', 'industry', 'wine'], blurb: 'Ironically named, actually fun. Natural wine and low-key cocktails.', lastVerified: '2026-04-01' },
  { id: 'ramona', name: 'Ramona', neighborhood: 'Greenpoint', address: '113 Franklin St, Brooklyn, NY 11222', lat: 40.7293, lng: -73.9575, priceTier: 3, tags: ['cocktail', 'date', 'garden', 'romantic', 'trendy'], blurb: 'Polished cocktails and a hidden garden out back.', lastVerified: '2026-04-01' },
  { id: 't-b-d', name: 't.b.d.', neighborhood: 'Greenpoint', address: '224 Franklin St, Brooklyn, NY 11222', lat: 40.733, lng: -73.9585, priceTier: 2, tags: ['beer', 'garden', 'buzzy', 'chill', 'locals'], blurb: 'Massive backyard. Warm-weather crowds and cold drafts.', lastVerified: '2026-04-01' },
  { id: 'the-diamond', name: 'The Diamond', neighborhood: 'Greenpoint', address: '43 Franklin St, Brooklyn, NY 11222', lat: 40.7295, lng: -73.9578, priceTier: 2, tags: ['beer', 'chill', 'locals', 'garden', 'old-nyc'], blurb: 'Cozy beer bar with shuffleboard and a leafy back patio.', lastVerified: '2026-04-01' },
  { id: 'barrio-chino', name: 'Barrio Chino', neighborhood: 'LES', address: '253 Broome St, New York, NY 10002', lat: 40.7176, lng: -73.9896, priceTier: 2, tags: ['cocktail', 'chill', 'locals', 'buzzy'], blurb: 'Tiny taqueria pouring serious tequila and mezcal margaritas.', lastVerified: '2026-04-01' },
  { id: 'beauty-and-essex', name: 'Beauty & Essex', neighborhood: 'LES', address: '146 Essex St, New York, NY 10002', lat: 40.7207, lng: -73.9873, priceTier: 3, tags: ['cocktail', 'speakeasy', 'buzzy', 'polished', 'date'], blurb: 'Hidden behind a pawn shop. Glamorous and buzzy.', lastVerified: '2026-04-01' },
  { id: 'clandestino', name: 'Clandestino', neighborhood: 'LES', address: '35 Canal St, New York, NY 10002', lat: 40.7143, lng: -73.9908, priceTier: 1, tags: ['dive', 'locals', 'cheap', 'chill'], blurb: 'Unpretentious neighborhood dive. Cheap drinks, no fuss.', lastVerified: '2026-04-01' },
  { id: 'loreley-beer-garden', name: 'Loreley Beer Garden', neighborhood: 'LES', address: '7 Rivington St, New York, NY 10002', lat: 40.7222, lng: -73.9925, priceTier: 2, tags: ['beer', 'garden', 'buzzy', 'post-work'], blurb: 'German brews in a big open-air backyard garden.', lastVerified: '2026-04-01' },
  { id: 'the-ten-bells', name: 'The Ten Bells', neighborhood: 'LES', address: '247 Broome St, New York, NY 10002', lat: 40.7175, lng: -73.9898, priceTier: 2, tags: ['wine', 'chill', 'date', 'indie'], blurb: 'Candlelit natural wine bar. Oysters and low light.', lastVerified: '2026-04-01' },
  { id: 'jimmys-corner-2', name: 'Jimmy\'s Corner', neighborhood: 'Midtown', address: '140 W 44th St, New York, NY 10036', lat: 40.7566, lng: -73.9847, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'old-nyc'], blurb: 'Boxing photos, stiff pours, zero pretense near Times Square.', lastVerified: '2026-04-01' },
  { id: 'refinery-rooftop', name: 'Refinery Rooftop', neighborhood: 'Midtown', address: '63 W 38th St, New York, NY 10018', lat: 40.7513, lng: -73.9848, priceTier: 3, tags: ['rooftop', 'cocktail', 'date', 'buzzy', 'instagrammable'], blurb: 'Glass-covered rooftop with Empire State views.', lastVerified: '2026-04-01' },
  { id: 'rudys-bar-and-grill', name: 'Rudy\'s Bar & Grill', neighborhood: 'Midtown', address: '627 9th Ave, New York, NY 10036', lat: 40.7591, lng: -73.9911, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'buzzy', 'old-nyc'], blurb: 'Free hot dogs with cheap pitchers. Pure dive.', lastVerified: '2026-04-01' },
  { id: 'russian-vodka-room', name: 'Russian Vodka Room', neighborhood: 'Midtown', address: '265 W 52nd St, New York, NY 10019', lat: 40.7636, lng: -73.9856, priceTier: 2, tags: ['cocktail', 'lounge', 'locals', 'old-nyc'], blurb: 'House-infused vodkas in a dim, hushed room.', lastVerified: '2026-04-01' },
  { id: 'the-ginger-man', name: 'The Ginger Man', neighborhood: 'Midtown', address: '11 E 36th St, New York, NY 10016', lat: 40.7487, lng: -73.9838, priceTier: 2, tags: ['beer', 'pub', 'post-work', 'buzzy'], blurb: 'Endless taps and casks. Beer-nerd heaven.', lastVerified: '2026-04-01' },
  { id: 'commonwealth', name: 'Commonwealth', neighborhood: 'Park Slope', address: '497 5th Ave, Brooklyn, NY 11215', lat: 40.6669, lng: -73.9877, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'chill'], blurb: 'Beloved neighborhood dive with a back patio.', lastVerified: '2026-04-01' },
  { id: 'loki-lounge', name: 'Loki Lounge', neighborhood: 'Park Slope', address: '304 5th Ave, Brooklyn, NY 11215', lat: 40.672, lng: -73.985, priceTier: 1, tags: ['dive', 'lounge', 'cheap', 'pub'], blurb: 'Dim longtime dive with a pool table in back.', lastVerified: '2026-04-01' },
  { id: 'mission-dolores', name: 'Mission Dolores', neighborhood: 'Park Slope', address: '249 4th Ave, Brooklyn, NY 11215', lat: 40.6789, lng: -73.9838, priceTier: 2, tags: ['beer', 'garden', 'chill', 'buzzy'], blurb: 'Covered beer garden built inside an old auto garage.', lastVerified: '2026-04-01' },
  { id: 'the-gate', name: 'The Gate', neighborhood: 'Park Slope', address: '321 5th Ave, Brooklyn, NY 11215', lat: 40.6726, lng: -73.9856, priceTier: 2, tags: ['beer', 'garden', 'locals', 'chill'], blurb: 'Huge draft list and a dog-friendly corner patio.', lastVerified: '2026-04-01' },
  { id: 'union-hall', name: 'Union Hall', neighborhood: 'Park Slope', address: '702 Union St, Brooklyn, NY 11215', lat: 40.6774, lng: -73.9836, priceTier: 2, tags: ['buzzy', 'live', 'cocktail', 'date', 'locals'], blurb: 'Bocce courts, taxidermy, and live bands downstairs.', lastVerified: '2026-04-01' },
  { id: 'american-trash', name: 'American Trash', neighborhood: 'UES', address: '1471 1st Ave, New York, NY 10075', lat: 40.7695, lng: -73.9535, priceTier: 1, tags: ['dive', 'rough', 'locals', 'cheap', 'loud'], blurb: 'Junk-covered walls, stiff pours. A proper UES dive.', lastVerified: '2026-04-01' },
  { id: 'dorrians-red-hand', name: 'Dorrian\'s Red Hand', neighborhood: 'UES', address: '1616 2nd Ave, New York, NY 10028', lat: 40.7775, lng: -73.9515, priceTier: 2, tags: ['pub', 'locals', 'buzzy', 'old-nyc'], blurb: 'Preppy UES institution. The neighborhood has drunk here for decades.', lastVerified: '2026-04-01' },
  { id: 'seamstress', name: 'Seamstress', neighborhood: 'UES', address: '339 E 75th St, New York, NY 10021', lat: 40.7705, lng: -73.9555, priceTier: 3, tags: ['cocktail', 'date', 'polished', 'speakeasy'], blurb: 'Serious cocktails behind a rustic front. Date-night reliable.', lastVerified: '2026-04-01' },
  { id: 'session-73', name: 'Session 73', neighborhood: 'UES', address: '1359 1st Ave, New York, NY 10021', lat: 40.7675, lng: -73.957, priceTier: 2, tags: ['live', 'jazz', 'buzzy', 'locals'], blurb: 'Free live music nightly. Jazz, funk, and regulars.', lastVerified: '2026-04-01' },
  { id: 'uva', name: 'Uva', neighborhood: 'UES', address: '1486 2nd Ave, New York, NY 10075', lat: 40.7725, lng: -73.956, priceTier: 2, tags: ['wine', 'romantic', 'date', 'chill'], blurb: 'Candlelit Italian wine bar. Linger over a bottle.', lastVerified: '2026-04-01' },
  { id: 'amsterdam-ale-house', name: 'Amsterdam Ale House', neighborhood: 'UWS', address: '340 Amsterdam Ave, New York, NY 10024', lat: 40.7808, lng: -73.9803, priceTier: 2, tags: ['pub', 'beer', 'post-work', 'locals'], blurb: 'Neighborhood pub with a serious tap list. Easy post-work pint.', lastVerified: '2026-04-01' },
  { id: 'bin-71', name: 'Bin 71', neighborhood: 'UWS', address: '237 Columbus Ave, New York, NY 10023', lat: 40.7787, lng: -73.9793, priceTier: 2, tags: ['wine', 'date', 'romantic', 'chill'], blurb: 'Cozy wine bar for a date. Small plates, big pours.', lastVerified: '2026-04-01' },
  { id: 'jacobs-pickles', name: 'Jacob\'s Pickles', neighborhood: 'UWS', address: '509 Amsterdam Ave, New York, NY 10024', lat: 40.7873, lng: -73.9757, priceTier: 2, tags: ['beer', 'buzzy', 'loud', 'post-work'], blurb: 'Southern comfort, biscuits, and a deep bourbon list. Always packed.', lastVerified: '2026-04-01' },
  { id: 'malachys-donegal-inn', name: 'Malachy\'s Donegal Inn', neighborhood: 'UWS', address: '103 W 72nd St, New York, NY 10023', lat: 40.7772, lng: -73.9803, priceTier: 1, tags: ['dive', 'locals', 'cheap', 'old-nyc'], blurb: 'Old-school West Side dive. Cheap, unpretentious, regulars only.', lastVerified: '2026-04-01' },
  { id: 'the-gin-mill', name: 'The Gin Mill', neighborhood: 'UWS', address: '442 Amsterdam Ave, New York, NY 10024', lat: 40.7849, lng: -73.9768, priceTier: 2, tags: ['dive', 'beer', 'loud', 'buzzy', 'locals'], blurb: 'Amsterdam Ave sports dive. Cheap beer, the game\'s always on.', lastVerified: '2026-04-01' },
  { id: 'corner-bistro', name: 'Corner Bistro', neighborhood: 'West Village', address: '331 W 4th St, New York, NY 10014', lat: 40.7383, lng: -74.0025, priceTier: 1, tags: ['dive', 'pub', 'beer', 'cheap', 'old-nyc'], blurb: 'Legendary burgers, cheap ale, worn wood. A Village institution.', lastVerified: '2026-04-01' },
  { id: 'kettle-of-fish', name: 'Kettle of Fish', neighborhood: 'West Village', address: '59 Christopher St, New York, NY 10014', lat: 40.7333, lng: -74.0026, priceTier: 1, tags: ['dive', 'locals', 'cheap', 'beer', 'chill'], blurb: 'Packers-bar dive. Couches, board games, cheap beer, no pretense.', lastVerified: '2026-04-01' },
  { id: 'maries-crisis-cafe', name: 'Marie\'s Crisis Cafe', neighborhood: 'West Village', address: '59 Grove St, New York, NY 10014', lat: 40.7331, lng: -74.0027, priceTier: 2, tags: ['live', 'old-nyc', 'locals', 'chill'], blurb: 'Show-tune piano singalongs nightly. Everyone knows every word.', lastVerified: '2026-04-01' },
  { id: 'the-happiest-hour', name: 'The Happiest Hour', neighborhood: 'West Village', address: '121 W 10th St, New York, NY 10011', lat: 40.7346, lng: -74.0006, priceTier: 3, tags: ['cocktail', 'speakeasy', 'buzzy', 'date'], blurb: 'Tiki-tinged cocktails upstairs, serious speakeasy Slowly Shirley below.', lastVerified: '2026-04-01' },
  { id: 'the-rusty-knot', name: 'The Rusty Knot', neighborhood: 'West Village', address: '425 West St, New York, NY 10014', lat: 40.7343, lng: -74.0098, priceTier: 2, tags: ['dive', 'chill', 'beer', 'locals'], blurb: 'Waterfront dive with tiki drinks and a pool table.', lastVerified: '2026-04-01' },
  { id: 'maison-premiere', name: 'Maison Premiere', neighborhood: 'Williamsburg', address: '298 Bedford Ave, Brooklyn, NY 11249', lat: 40.7145, lng: -73.9614, priceTier: 3, tags: ['cocktail', 'romantic', 'date', 'speakeasy', 'old-nyc'], blurb: 'Absinthe, oysters, and old-world glamour. Bring a date.', lastVerified: '2026-04-01' },
  { id: 'radegast-hall-biergarten', name: 'Radegast Hall & Biergarten', neighborhood: 'Williamsburg', address: '113 N 3rd St, Brooklyn, NY 11249', lat: 40.7178, lng: -73.9618, priceTier: 2, tags: ['beer', 'pub', 'loud', 'buzzy', 'live'], blurb: 'Bavarian beer hall. Sausages, steins, and live music.', lastVerified: '2026-04-01' },
  { id: 'rocka-rolla', name: 'Rocka Rolla', neighborhood: 'Williamsburg', address: '486 Metropolitan Ave, Brooklyn, NY 11211', lat: 40.7137, lng: -73.9527, priceTier: 1, tags: ['dive', 'loud', 'cheap', 'locals', 'rough'], blurb: 'Cheap beer, loud rock, zero pretense.', lastVerified: '2026-04-01' },
  { id: 'spuyten-duyvil', name: 'Spuyten Duyvil', neighborhood: 'Williamsburg', address: '359 Metropolitan Ave, Brooklyn, NY 11211', lat: 40.7135, lng: -73.9553, priceTier: 2, tags: ['beer', 'chill', 'garden', 'locals', 'indie'], blurb: 'Rare Belgian and craft beers. Quiet back garden.', lastVerified: '2026-04-01' },
  { id: 'the-ides-bar', name: 'The Ides Bar', neighborhood: 'Williamsburg', address: '80 Wythe Ave, Brooklyn, NY 11249', lat: 40.7223, lng: -73.9582, priceTier: 3, tags: ['rooftop', 'cocktail', 'buzzy', 'date', 'instagrammable'], blurb: 'Rooftop skyline views. Come at sunset to impress.', lastVerified: '2026-04-01' },
];
