import type { Bar } from '@/types';
import { extraBars } from './bars.extra';

// IMPORTANT: lastVerified dates below are PLACEHOLDERS so all bars pass the
// 180-day hard filter and the app remains functional. Hours/specials/blurbs
// have NOT been personally verified within the v0.2 schema. Real curation
// (call/visit/site-check each bar) is tracked as PRD risk R4 and must happen
// before any public launch where the app makes factual claims about named
// businesses. Update lastVerified per-bar as each is verified.

const PLACEHOLDER_VERIFIED = '2026-04-01';

const coreBars: Bar[] = [
  // ---- LES (5) ----
  {
    id: 'attaboy',
    name: 'Attaboy',
    neighborhood: 'LES',
    address: '134 Eldridge St',
    lat: 40.7188,
    lng: -73.9926,
    priceTier: 3,
    tags: ['cocktail', 'speakeasy', 'polished', 'industry', 'pricey'],
    blurb: 'No menu. Tell them what you like. They build it.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'mr-purple',
    name: 'Mr. Purple',
    neighborhood: 'LES',
    address: '180 Orchard St',
    lat: 40.7211,
    lng: -73.9874,
    priceTier: 3,
    tags: ['rooftop', 'trendy', 'instagrammable', 'buzzy', 'pricey', 'house'],
    blurb: 'Rooftop with skyline views. Bring people to impress.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: '169-bar',
    name: '169 Bar',
    neighborhood: 'LES',
    address: '169 East Broadway',
    lat: 40.7142,
    lng: -73.9890,
    priceTier: 1,
    tags: ['dive', 'rough', 'old-nyc', 'cheap', 'locals', 'indie'],
    blurb: 'Stuffed peacock on the wall. Cheap drinks. Anything goes.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'welcome-johnsons',
    name: 'Welcome to the Johnsons',
    neighborhood: 'LES',
    address: '123 Rivington St',
    lat: 40.7202,
    lng: -73.9876,
    priceTier: 1,
    tags: ['dive', 'cheap', 'locals', 'rough', 'old-nyc', 'indie'],
    blurb: 'Wood paneling, sticky floors, jukebox. The original.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'pianos',
    name: 'Pianos',
    neighborhood: 'LES',
    address: '158 Ludlow St',
    lat: 40.7212,
    lng: -73.9863,
    priceTier: 2,
    tags: ['live', 'buzzy', 'loud', 'mid', 'trendy'],
    blurb: 'Live music downstairs, packed bar upstairs. Always something.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- East Village (5) ----
  {
    id: 'death-and-co',
    name: 'Death & Co',
    neighborhood: 'East Village',
    address: '433 E 6th St',
    lat: 40.7256,
    lng: -73.9826,
    priceTier: 3,
    tags: ['cocktail', 'polished', 'date', 'pricey', 'industry'],
    blurb: 'Cocktail temple. Bring it for date night.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'pdt',
    name: 'PDT',
    neighborhood: 'East Village',
    address: '113 St Marks Pl',
    lat: 40.7282,
    lng: -73.9844,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'polished', 'date', 'pricey'],
    blurb: 'Phone booth in a hot dog shop. You know the one.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'amor-y-amargo',
    name: 'Amor y Amargo',
    neighborhood: 'East Village',
    address: '443 E 6th St',
    lat: 40.7256,
    lng: -73.9821,
    priceTier: 3,
    tags: ['cocktail', 'lounge', 'chill', 'industry', 'pricey'],
    blurb: 'Tiny bitters bar. Sit at the counter.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'holiday-cocktail-lounge',
    name: 'Holiday Cocktail Lounge',
    neighborhood: 'East Village',
    address: '75 St Marks Pl',
    lat: 40.7280,
    lng: -73.9866,
    priceTier: 2,
    tags: ['cocktail', 'old-nyc', 'locals', 'mid', 'lounge'],
    blurb: 'Old St. Marks institution. Red walls, regulars, perfect drinks.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'ace-bar',
    name: 'Ace Bar',
    neighborhood: 'East Village',
    address: '531 E 5th St',
    lat: 40.7257,
    lng: -73.9805,
    priceTier: 1,
    tags: ['dive', 'pub', 'cheap', 'locals', 'buzzy'],
    blurb: 'Pool tables, skee-ball, pinball, beer. No pretense.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- West Village (5) ----
  {
    id: 'employees-only',
    name: 'Employees Only',
    neighborhood: 'West Village',
    address: '510 Hudson St',
    lat: 40.7338,
    lng: -74.0067,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'industry', 'pricey', 'date'],
    blurb: 'Psychic in the window, late kitchen, fortunes told nightly.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'little-branch',
    name: 'Little Branch',
    neighborhood: 'West Village',
    address: '22 7th Ave S',
    lat: 40.7305,
    lng: -74.0028,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'jazz', 'date', 'pricey', 'lounge'],
    blurb: 'Down the stairs. Live jazz nightly. Order off-menu.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'white-horse-tavern',
    name: 'White Horse Tavern',
    neighborhood: 'West Village',
    address: '567 Hudson St',
    lat: 40.7361,
    lng: -74.0058,
    priceTier: 2,
    tags: ['pub', 'old-nyc', 'locals', 'mid', 'beer'],
    blurb: 'Dylan Thomas drank here. So can you.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'smalls-jazz-club',
    name: 'Smalls Jazz Club',
    neighborhood: 'West Village',
    address: '183 W 10th St',
    lat: 40.7332,
    lng: -74.0026,
    priceTier: 3,
    tags: ['jazz', 'live', 'lounge', 'mid', 'pricey'],
    blurb: 'Cellar jazz, every night, since 1994.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'buvette',
    name: 'Buvette',
    neighborhood: 'West Village',
    address: '42 Grove St',
    lat: 40.7325,
    lng: -74.0050,
    priceTier: 3,
    tags: ['wine', 'romantic', 'date', 'polished', 'chill', 'pricey'],
    blurb: 'Parisian gastrothèque. Tiny tables. Lean in.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- Chelsea (5) ----
  {
    id: 'bathtub-gin',
    name: 'Bathtub Gin',
    neighborhood: 'Chelsea',
    address: '132 9th Ave',
    lat: 40.7413,
    lng: -74.0042,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'polished', 'date', 'pricey'],
    blurb: 'Behind the coffee shop door. Bathtub in the middle of the room.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'the-tippler',
    name: 'The Tippler',
    neighborhood: 'Chelsea',
    address: '425 W 15th St',
    lat: 40.7424,
    lng: -74.0064,
    priceTier: 2,
    tags: ['cocktail', 'lounge', 'buzzy', 'mid', 'post-work'],
    blurb: 'Under Chelsea Market. Wood, brick, classic shakes.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'le-bain',
    name: 'Le Bain',
    neighborhood: 'Chelsea',
    address: '444 W 13th St',
    lat: 40.7407,
    lng: -74.0085,
    priceTier: 4,
    tags: ['rooftop', 'dance', 'house', 'trendy', 'instagrammable', 'splurge', 'loud'],
    blurb: 'Standard Hotel rooftop. Crepes after dancing. Hudson views.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'tia-pol',
    name: 'Tia Pol',
    neighborhood: 'Chelsea',
    address: '205 10th Ave',
    lat: 40.7470,
    lng: -74.0033,
    priceTier: 3,
    tags: ['wine', 'chill', 'date', 'polished', 'mid'],
    blurb: 'Spanish wine bar. Tinned fish, jamón, sit at the counter.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'the-frying-pan',
    name: 'The Frying Pan',
    neighborhood: 'Chelsea',
    address: 'Pier 66, 11th Ave & W 26th St',
    lat: 40.7497,
    lng: -74.0094,
    priceTier: 2,
    tags: ['beer', 'buzzy', 'tourist', 'mid', 'live', 'loud'],
    blurb: 'Boat bar on the Hudson. Summer-only mood, all year.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- FiDi (5) ----
  {
    id: 'dead-rabbit',
    name: 'The Dead Rabbit',
    neighborhood: 'FiDi',
    address: '30 Water St',
    lat: 40.7032,
    lng: -74.0117,
    priceTier: 3,
    tags: ['cocktail', 'pub', 'polished', 'industry', 'pricey'],
    blurb: 'Three floors of Irish hospitality. World-class cocktails upstairs.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'fraunces-tavern',
    name: 'Fraunces Tavern',
    neighborhood: 'FiDi',
    address: '54 Pearl St',
    lat: 40.7037,
    lng: -74.0119,
    priceTier: 2,
    tags: ['old-nyc', 'pub', 'tourist', 'beer', 'mid'],
    blurb: 'Washington said goodbye to his officers here. So can you.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'ulysses-folk-house',
    name: "Ulysses' Folk House",
    neighborhood: 'FiDi',
    address: '95 Pearl St',
    lat: 40.7046,
    lng: -74.0103,
    priceTier: 2,
    tags: ['pub', 'buzzy', 'post-work', 'beer', 'mid'],
    blurb: 'Stone Street institution. Loud at 6pm, louder by 9.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'trinity-place',
    name: 'Trinity Place',
    neighborhood: 'FiDi',
    address: '115 Broadway',
    lat: 40.7081,
    lng: -74.0117,
    priceTier: 3,
    tags: ['cocktail', 'lounge', 'polished', 'post-work', 'mid'],
    blurb: 'Drinks inside a 1904 bank vault. Order something stiff.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'pier-a',
    name: 'Pier A Harbor House',
    neighborhood: 'FiDi',
    address: '22 Battery Pl',
    lat: 40.7037,
    lng: -74.0166,
    priceTier: 2,
    tags: ['beer', 'tourist', 'buzzy', 'mid', 'rooftop'],
    blurb: 'Outdoor deck on the harbor. Long beer list, longer sunsets.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- Midtown (5) ----
  {
    id: 'the-campbell',
    name: 'The Campbell',
    neighborhood: 'Midtown',
    address: '15 Vanderbilt Ave',
    lat: 40.7527,
    lng: -73.9772,
    priceTier: 3,
    tags: ['cocktail', 'polished', 'post-work', 'pricey', 'old-nyc'],
    blurb: 'Inside Grand Central. Drink in a 1920s railroad-tycoon office.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'rum-house',
    name: 'The Rum House',
    neighborhood: 'Midtown',
    address: '228 W 47th St',
    lat: 40.7596,
    lng: -73.9846,
    priceTier: 3,
    tags: ['jazz', 'live', 'cocktail', 'polished', 'lounge', 'mid'],
    blurb: 'Live jazz nightly. Bartenders in white coats. Theater-district secret.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'bar-sixtyfive',
    name: 'Bar SixtyFive',
    neighborhood: 'Midtown',
    address: '30 Rockefeller Plaza, 65th fl',
    lat: 40.7587,
    lng: -73.9787,
    priceTier: 4,
    tags: ['rooftop', 'cocktail', 'date', 'splurge', 'polished', 'instagrammable'],
    blurb: 'Rainbow Room views without the dinner-jacket commitment.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'jimmys-corner',
    name: "Jimmy's Corner",
    neighborhood: 'Midtown',
    address: '140 W 44th St',
    lat: 40.7570,
    lng: -73.9847,
    priceTier: 1,
    tags: ['dive', 'old-nyc', 'cheap', 'locals', 'pub'],
    blurb: 'Boxing photos on every inch of wall. The opposite of Times Square.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'pj-clarkes',
    name: "P.J. Clarke's",
    neighborhood: 'Midtown',
    address: '915 3rd Ave',
    lat: 40.7593,
    lng: -73.9683,
    priceTier: 2,
    tags: ['pub', 'old-nyc', 'post-work', 'beer', 'mid', 'locals'],
    blurb: 'Sinatra burger, sawdust floors, 1884 saloon energy.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- UWS (5) ----
  {
    id: 'manhattan-cricket-club',
    name: 'Manhattan Cricket Club',
    neighborhood: 'UWS',
    address: '226 W 79th St',
    lat: 40.7837,
    lng: -73.9794,
    priceTier: 3,
    tags: ['speakeasy', 'cocktail', 'polished', 'date', 'pricey', 'lounge'],
    blurb: 'Above Burke & Wills. Press the buzzer. Wear something.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'owls-tail',
    name: "The Owl's Tail",
    neighborhood: 'UWS',
    address: '215 W 75th St',
    lat: 40.7820,
    lng: -73.9806,
    priceTier: 2,
    tags: ['cocktail', 'lounge', 'chill', 'date', 'mid'],
    blurb: 'Dim, narrow, sound of a good evening. Order the Old Fashioned.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'dive-bar-uws',
    name: 'Dive Bar',
    neighborhood: 'UWS',
    address: '732 Amsterdam Ave',
    lat: 40.7888,
    lng: -73.9745,
    priceTier: 1,
    tags: ['dive', 'cheap', 'locals', 'pub', 'beer'],
    blurb: 'It says what it is. UWS regulars, fish tank, cheap pours.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'dead-poet',
    name: 'The Dead Poet',
    neighborhood: 'UWS',
    address: '450 Amsterdam Ave',
    lat: 40.7836,
    lng: -73.9789,
    priceTier: 2,
    tags: ['pub', 'locals', 'old-nyc', 'beer', 'mid'],
    blurb: 'Irish pub named for poets. Whiskey list longer than the menu.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'prohibition',
    name: 'Prohibition',
    neighborhood: 'UWS',
    address: '503 Columbus Ave',
    lat: 40.7869,
    lng: -73.9756,
    priceTier: 2,
    tags: ['live', 'buzzy', 'mid', 'cocktail', 'post-work'],
    blurb: 'Live music seven nights. UWS that forgot it was UWS.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },

  // ---- UES (5) ----
  {
    id: 'bemelmans-bar',
    name: 'Bemelmans Bar',
    neighborhood: 'UES',
    address: '35 E 76th St',
    lat: 40.7740,
    lng: -73.9636,
    priceTier: 4,
    tags: ['cocktail', 'jazz', 'live', 'polished', 'splurge', 'date', 'old-nyc'],
    blurb: 'Madeline murals, piano nightly, cover charge worth every cent.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'subway-inn',
    name: 'The Subway Inn',
    neighborhood: 'UES',
    address: '1140 2nd Ave',
    lat: 40.7613,
    lng: -73.9627,
    priceTier: 1,
    tags: ['dive', 'cheap', 'old-nyc', 'locals', 'rough'],
    blurb: 'They moved it, the soul came with. Cash bar, neon sign, no questions.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'the-penrose',
    name: 'The Penrose',
    neighborhood: 'UES',
    address: '1590 2nd Ave',
    lat: 40.7775,
    lng: -73.9540,
    priceTier: 2,
    tags: ['pub', 'mid', 'buzzy', 'post-work', 'beer', 'locals'],
    blurb: 'Gastropub the neighborhood actually goes to. Long bar, good fries.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'auction-house',
    name: 'The Auction House',
    neighborhood: 'UES',
    address: '300 E 89th St',
    lat: 40.7807,
    lng: -73.9519,
    priceTier: 2,
    tags: ['lounge', 'chill', 'date', 'romantic', 'mid', 'cocktail'],
    blurb: 'Velvet couches, low light, fireplace. Conversation bar.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
  {
    id: 'caledonia-bar',
    name: 'Caledonia Bar',
    neighborhood: 'UES',
    address: '1609 2nd Ave',
    lat: 40.7780,
    lng: -73.9527,
    priceTier: 3,
    tags: ['lounge', 'chill', 'industry', 'pricey', 'polished'],
    blurb: 'Scotch list deeper than the Hudson. Order something peaty.',
    lastVerified: PLACEHOLDER_VERIFIED,
  },
];

// Core Manhattan set + the curated Manhattan-depth/Brooklyn expansion.
export const bars: Bar[] = [...coreBars, ...extraBars];
