import type { Bar } from '@/types';

// Catalog EXPANSION pass 4 (2026-07-24) — thin-neighborhood top-up to ~24 open
// bars each (Greenpoint/UWS/Bushwick/East Village/Chelsea/FiDi/Midtown/UES).
// Proposed by a per-neighborhood agent fan-out (JSON-schema-constrained,
// web-search-encouraged), adversarially reviewed (existence / closure /
// neighborhood / dedup / address), then deterministically assembled (catalog
// dedup + bbox + quota). Full decision trail in the PR that introduced it.
//
// Coords are best-effort from the sourced addresses — the targeted Places
// refresh (scripts/refresh-places.mjs --only ...) corrects them and adds
// hours/photos; bars it flags as closed/mismatched get removed before merge.
export const expansion4Bars: Bar[] = [
  // Bushwick
  { id: 'jupiter-disco', name: 'Jupiter Disco', neighborhood: 'Bushwick', address: '1237 Flushing Ave, Brooklyn, NY 11237', lat: 40.7082, lng: -73.9235, priceTier: 2, tags: ['cocktail', 'dance', 'house', 'trendy', 'buzzy', 'mid'], blurb: 'Sci-fi bunker cocktails, analog synths, DJs till 4am.', lastVerified: '2026-07-24' },
  { id: 'the-narrows', name: 'The Narrows', neighborhood: 'Bushwick', address: '1037 Flushing Ave, Brooklyn, NY 11237', lat: 40.707, lng: -73.9331, priceTier: 2, tags: ['cocktail', 'date', 'garden', 'romantic', 'chill', 'mid'], blurb: 'Art-deco sliver bar; mezcal up front, garden out back.', lastVerified: '2026-07-24' },
  { id: 'yours-sincerely', name: 'Yours Sincerely', neighborhood: 'Bushwick', address: '41 Wilson Ave, Brooklyn, NY 11237', lat: 40.7037, lng: -73.93, priceTier: 2, tags: ['cocktail', 'speakeasy', 'date', 'trendy', 'chill', 'mid'], blurb: 'Beaker cocktails on tap in a candlelit lab. $6 happy hour.', lastVerified: '2026-07-24' },
  { id: 'hart-bar', name: 'Hart Bar', neighborhood: 'Bushwick', address: '538 Hart St, Brooklyn, NY 11221', lat: 40.697, lng: -73.927, priceTier: 2, tags: ['cocktail', 'live', 'chill', 'locals', 'date', 'mid'], blurb: 'Corner-bar cocktails and living-room ease off the JMZ.', lastVerified: '2026-07-24' },
  { id: 'old-stanleys', name: 'Old Stanley\'s', neighborhood: 'Bushwick', address: '226 Wyckoff Ave, Brooklyn, NY 11237', lat: 40.701, lng: -73.9155, priceTier: 1, tags: ['dive', 'beer', 'garden', 'cheap', 'locals'], blurb: 'Cash-only pints till 4am. Backyard, zero frills.', lastVerified: '2026-07-24' },
  // Chelsea
  { id: 'la-noxe', name: 'La Noxe', neighborhood: 'Chelsea', address: '315 7th Ave, New York, NY 10001', lat: 40.747, lng: -73.9932, priceTier: 3, tags: ['speakeasy', 'cocktail', 'date', 'romantic', 'pricey'], blurb: 'Duck down the 28th St subway stairs. Velvet nook, 30 seats, killer martinis.', lastVerified: '2026-07-24' },
  { id: 'westside-tavern', name: 'Westside Tavern', neighborhood: 'Chelsea', address: '360 W 23rd St, New York, NY 10011', lat: 40.7464, lng: -74.0005, priceTier: 1, tags: ['dive', 'beer', 'cheap', 'locals', 'chill'], blurb: 'Pool table, jukebox, cheap pints till 4am. Chelsea\'s true neighborhood dive.', lastVerified: '2026-07-24' },
  { id: 'copper-still-chelsea', name: 'The Copper Still Chelsea', neighborhood: 'Chelsea', address: '206 7th Ave, New York, NY 10011', lat: 40.7434, lng: -73.9958, priceTier: 2, tags: ['pub', 'beer', 'post-work', 'buzzy', 'mid'], blurb: 'Irish-owned whiskey pub, 300 bottles deep. Post-work crowd spills to the bar.', lastVerified: '2026-07-24' },
  { id: 'g-lounge', name: 'g Lounge', neighborhood: 'Chelsea', address: '225 W 19th St, New York, NY 10011', lat: 40.7429, lng: -73.9985, priceTier: 2, tags: ['dance', 'lounge', 'buzzy', 'trendy', 'mid'], blurb: 'The 90s queer icon reborn in 2025 — disco lights on, everyone welcome.', lastVerified: '2026-07-24' },
  // East Village
  { id: 'berlin', name: 'Berlin', neighborhood: 'East Village', address: '25 Avenue A, New York, NY 10009', lat: 40.7228, lng: -73.984, priceTier: 2, tags: ['live', 'indie', 'dive', 'loud', 'buzzy', 'mid'], blurb: 'Unmarked stairs under 2A. Sweaty basement rock and DJs \'til 4am.', lastVerified: '2026-07-24' },
  { id: 'mister-paradise', name: 'Mister Paradise', neighborhood: 'East Village', address: '105 1st Ave, New York, NY 10003', lat: 40.7261, lng: -73.9862, priceTier: 3, tags: ['cocktail', 'trendy', 'buzzy', 'date', 'pricey'], blurb: 'Serious cocktails with joke names. Retro glow, flirty chaos.', lastVerified: '2026-07-24' },
  { id: 'sake-bar-decibel', name: 'Sake Bar Decibel', neighborhood: 'East Village', address: '240 E 9th St, New York, NY 10003', lat: 40.7293, lng: -73.9878, priceTier: 2, tags: ['speakeasy', 'date', 'old-nyc', 'chill', 'mid'], blurb: 'Basement sake den since 1993. Graffiti walls, blinking On Air sign.', lastVerified: '2026-07-24' },
  { id: 'blue-and-gold-tavern', name: 'Blue & Gold Tavern', neighborhood: 'East Village', address: '79 E 7th St, New York, NY 10003', lat: 40.7273, lng: -73.9857, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'chill'], blurb: '$6 drafts, pool table, jukebox. Bring cash, lose the evening.', lastVerified: '2026-07-24' },
  // FiDi
  { id: 'split-eights', name: 'Split Eights', neighborhood: 'FiDi', address: '40 Exchange Pl, New York, NY 10005', lat: 40.7056, lng: -74.0101, priceTier: 3, tags: ['cocktail', 'date', 'trendy', 'chill', 'pricey'], blurb: 'Coffee by day, $18 classics by night. FiDi\'s rare actually-cool cocktail room.', lastVerified: '2026-07-24' },
  { id: 'white-horse-tavern-fidi', name: 'White Horse Tavern (Financial District)', neighborhood: 'FiDi', address: '25 Bridge St, New York, NY 10004', lat: 40.7037, lng: -74.0125, priceTier: 2, tags: ['dive', 'old-nyc', 'locals', 'chill', 'mid'], blurb: 'No-frills corner tavern pouring since 1933. The un-Wall-Street Wall Street bar.', lastVerified: '2026-07-24' },
  { id: 'the-malt-house-fidi', name: 'The Malt House FiDi', neighborhood: 'FiDi', address: '9 Maiden Ln, New York, NY 10038', lat: 40.7096, lng: -74.0089, priceTier: 2, tags: ['beer', 'pub', 'post-work', 'buzzy', 'mid'], blurb: 'Three floors and 7,000 sq ft of taps. Where FiDi loosens its tie at 5:01.', lastVerified: '2026-07-24' },
  { id: 'hide-rooftop', name: 'Hide Rooftop', neighborhood: 'FiDi', address: '24 John St, New York, NY 10038', lat: 40.7098, lng: -74.0077, priceTier: 3, tags: ['rooftop', 'cocktail', 'date', 'instagrammable', 'trendy', 'pricey'], blurb: '20th-floor sky bar hidden above John St. Skyline views without the Manhatta bill.', lastVerified: '2026-07-24' },
  // Greenpoint
  { id: 'good-room', name: 'Good Room', neighborhood: 'Greenpoint', address: '98 Meserole Ave, Brooklyn, NY 11222', lat: 40.7272, lng: -73.9535, priceTier: 2, tags: ['dance', 'house', 'loud', 'buzzy', 'mid'], blurb: 'Two rooms, a real soundsystem, house till 4am. Greenpoint\'s proper dance floor.', lastVerified: '2026-07-24' },
  { id: 'moonlight-mile', name: 'The Moonlight Mile', neighborhood: 'Greenpoint', address: '200 Franklin St, Brooklyn, NY 11222', lat: 40.7315, lng: -73.9583, priceTier: 2, tags: ['cocktail', 'beer', 'chill', 'locals', 'mid'], blurb: '200 American whiskeys and Stones on the stereo. Neighborhood, not scene.', lastVerified: '2026-07-24' },
  { id: 'diamond-lil', name: 'Diamond Lil', neighborhood: 'Greenpoint', address: '179 Nassau Ave, Brooklyn, NY 11222', lat: 40.7245, lng: -73.9478, priceTier: 2, tags: ['cocktail', 'date', 'romantic', 'polished', 'mid'], blurb: 'Velvet booths, mosaic floor, Mae West energy. Cocktails till 3am.', lastVerified: '2026-07-24' },
  { id: 'eavesdrop', name: 'Eavesdrop', neighborhood: 'Greenpoint', address: '674 Manhattan Ave, Brooklyn, NY 11222', lat: 40.7254, lng: -73.9513, priceTier: 3, tags: ['cocktail', 'wine', 'trendy', 'date', 'chill', 'pricey'], blurb: 'Audiophile listening room: vinyl, natural wine, hushed reverence.', lastVerified: '2026-07-24' },
  { id: 'capri-social-club', name: 'The Capri Social Club', neighborhood: 'Greenpoint', address: '156 Calyer St, Brooklyn, NY 11222', lat: 40.7268, lng: -73.9553, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'old-nyc', 'chill'], blurb: 'Century-old dive. Jello shots, High Life, zero irony.', lastVerified: '2026-07-24' },
  { id: 'keg-and-lantern', name: 'Keg & Lantern Brewing Company', neighborhood: 'Greenpoint', address: '97 Nassau Ave, Brooklyn, NY 11222', lat: 40.7243, lng: -73.9508, priceTier: 2, tags: ['beer', 'pub', 'post-work', 'locals', 'mid'], blurb: 'House-brewed pints and wings. The game\'s on, always.', lastVerified: '2026-07-24' },
  { id: 'twins-lounge', name: 'Twins Lounge', neighborhood: 'Greenpoint', address: '732 Manhattan Ave, Brooklyn, NY 11222', lat: 40.7266, lng: -73.9518, priceTier: 2, tags: ['lounge', 'dance', 'buzzy', 'locals', 'mid'], blurb: 'Bilevel pool-lounge-meets-disco. Racks up, lights down, open till 4.', lastVerified: '2026-07-24' },
  { id: 'temkins-bar', name: 'Temkin\'s Bar', neighborhood: 'Greenpoint', address: '155 Greenpoint Ave, Brooklyn, NY 11222', lat: 40.7303, lng: -73.9528, priceTier: 1, tags: ['dive', 'cheap', 'chill', 'locals'], blurb: 'Roomy vintage dive with pinball in back. Happy hour runs four hours.', lastVerified: '2026-07-24' },
  // Midtown
  { id: 'tanner-smiths', name: 'Tanner Smith\'s', neighborhood: 'Midtown', address: '204 W 55th St, New York, NY 10019', lat: 40.7648, lng: -73.9814, priceTier: 3, tags: ['cocktail', 'buzzy', 'date', 'post-work', 'pricey'], blurb: 'Prohibition swagger, proper cocktails, open till 4. Midtown\'s rare actual scene.', lastVerified: '2026-07-24' },
  { id: 'dutch-freds', name: 'Dutch Fred\'s', neighborhood: "Hell's Kitchen", address: '307 W 47th St, New York, NY 10036', lat: 40.7608, lng: -73.9877, priceTier: 2, tags: ['cocktail', 'buzzy', 'post-work', 'date', 'mid'], blurb: '1920s cocktails till 3am. Theater crowd piles in post-curtain, every night.', lastVerified: '2026-07-24' },
  { id: 'the-gaf-west', name: 'The Gaf West', neighborhood: "Hell's Kitchen", address: '401 W 48th St, New York, NY 10036', lat: 40.7629, lng: -73.9903, priceTier: 1, tags: ['dive', 'pub', 'cheap', 'locals', 'chill'], blurb: 'Darts, cheap pints, free comedy in the basement. Hell\'s Kitchen at its loosest.', lastVerified: '2026-07-24' },
  { id: 'beer-culture', name: 'Beer Culture', neighborhood: "Hell's Kitchen", address: '328 W 45th St, New York, NY 10036', lat: 40.7596, lng: -73.9893, priceTier: 2, tags: ['beer', 'chill', 'locals', 'post-work', 'mid'], blurb: '500 bottles, sharp taps, couch-corner calm two blocks off the theater crush.', lastVerified: '2026-07-24' },
  // UES
  { id: 'keys-and-heels', name: 'Keys & Heels', neighborhood: 'UES', address: '1488 2nd Ave, New York, NY 10075', lat: 40.7707, lng: -73.9556, priceTier: 3, tags: ['speakeasy', 'cocktail', 'date', 'polished', 'trendy', 'pricey'], blurb: 'Locksmith storefront, plush cocktail den behind. From the Uva team.', lastVerified: '2026-07-24' },
  { id: 'reifs-tavern', name: 'Reif\'s Tavern', neighborhood: 'UES', address: '302 E 92nd St, New York, NY 10128', lat: 40.7823, lng: -73.9491, priceTier: 1, tags: ['dive', 'cheap', 'locals', 'old-nyc', 'garden', 'chill'], blurb: 'Grill-your-own backyard, pool table, cheap cans. Unchanged since 1942.', lastVerified: '2026-07-24' },
  { id: 'ues-speakeasy', name: 'UES.', neighborhood: 'UES', address: '1707 2nd Ave, New York, NY 10128', lat: 40.7778, lng: -73.9502, priceTier: 3, tags: ['speakeasy', 'cocktail', 'date', 'instagrammable', 'pricey'], blurb: 'Order a scoop, slip past the ice-cream cartons into Storage.', lastVerified: '2026-07-24' },
  { id: 'iggys', name: 'Iggy\'s', neighborhood: 'UES', address: '1452 2nd Ave, New York, NY 10021', lat: 40.7702, lng: -73.9569, priceTier: 1, tags: ['dive', 'cheap', 'loud', 'buzzy', 'locals'], blurb: 'Karaoke till 4am with a bar full of strangers cheering you on.', lastVerified: '2026-07-24' },
  // UWS
  { id: 'es-bar', name: 'e\'s Bar', neighborhood: 'UWS', address: '511 Amsterdam Ave, New York, NY 10024', lat: 40.7867, lng: -73.9758, priceTier: 2, tags: ['beer', 'pub', 'chill', 'locals', 'mid'], blurb: 'Board games, cold beer, zero attitude. The UWS living room.', lastVerified: '2026-07-24' },
  { id: 'nobody-told-me', name: 'Nobody Told Me', neighborhood: 'UWS', address: '951 Amsterdam Ave, New York, NY 10025', lat: 40.8018, lng: -73.9646, priceTier: 3, tags: ['cocktail', 'date', 'trendy', 'buzzy', 'pricey'], blurb: '$2 happy-hour oysters and playful cocktails. Date-night sleeper.', lastVerified: '2026-07-24' },
  { id: 'broadway-dive', name: 'Broadway Dive', neighborhood: 'UWS', address: '2662 Broadway, New York, NY 10025', lat: 40.7993, lng: -73.9686, priceTier: 1, tags: ['dive', 'beer', 'cheap', 'locals', 'chill'], blurb: 'A dive with 30 craft taps and cask ale. Open till 4am.', lastVerified: '2026-07-24' },
  { id: 'caledonia-uws', name: 'Caledonia UWS', neighborhood: 'UWS', address: '424 Amsterdam Ave, New York, NY 10024', lat: 40.7838, lng: -73.9779, priceTier: 3, tags: ['cocktail', 'chill', 'date', 'locals', 'pricey'], blurb: '100+ whiskies, Islay peat heavy. Talk quietly, sip slowly.', lastVerified: '2026-07-24' },
  { id: 'dakota-bar', name: 'The Dakota Bar', neighborhood: 'UWS', address: '53 W 72nd St, New York, NY 10023', lat: 40.777, lng: -73.9765, priceTier: 3, tags: ['cocktail', 'date', 'romantic', 'locals', 'pricey'], blurb: 'Candlelit cocktails off Columbus, pouring till 3am.', lastVerified: '2026-07-24' },
];
