import type { PlacePatch } from '@/types';

// GENERATED FILE — do not edit by hand.
// Regenerated by `scripts/refresh-places.mjs` from the Google Places API weekly
// refresh (coords, opening hours, business status). Keyed by bar id; overlaid
// onto the curated catalog in bars.ts. Starts empty (no Places key wired yet) —
// an empty map is a no-op, so the catalog behaves exactly as before until the
// refresh job runs.
export const placesData: Record<string, PlacePatch> = {};
