// CEO orchestrator hard gate.
//
// Mirrors scripts/loop-guard.mjs (console.error + non-zero exit) but is an ALLOWLIST, not a
// denylist. That is a deliberate rewrite after the 2026-07-26 security review found the first
// denylist version trivially evadable: `notify`, `publish`, `release`, `promote`, `sql_exec`,
// `terraform_apply`, and every gerund (`sending_email`, `deploying_hotfix`) sailed straight
// through under LOOP_UNATTENDED=1 because they matched none of the keyword patterns.
//
// The action label is generated by an LLM. You cannot enumerate every synonym it will invent, so
// the only sound shape is: a fixed set of known actions per capability, and ANYTHING ELSE ABORTS.
// A new legitimate action requires a human to add it here — that is the intended cost.

import { isDeepStrictEqual } from 'node:util';
import { assertValidCeoState } from '../ceo/state.schema.mjs';

export class CeoGuardAbort extends Error {
  constructor(message) {
    super(message);
    this.name = 'CeoGuardAbort';
  }
}

export const CAPABILITIES = Object.freeze({
  RESEARCH: 'RESEARCH',
  DRAFT: 'DRAFT',
  MUTATE_BRANCH: 'MUTATE_BRANCH',
  MUTATE_PROD: 'MUTATE_PROD',
  CONTACT_EXTERNAL: 'CONTACT_EXTERNAL',
  SPEND: 'SPEND',
});

/** Branches the orchestrator may never land on directly, attended or not. */
export const PROTECTED_BRANCHES = Object.freeze(['main', 'master']);

/**
 * The allowlist. Capability -> the exact actions it may perform.
 *
 * CONTACT_EXTERNAL and SPEND map to the empty set: they are declared so an action carrying them
 * is recognised (and reported precisely) rather than falling into "unknown capability", but no
 * action is ever permitted under them.
 */
export const ALLOWED = Object.freeze({
  RESEARCH: Object.freeze([
    'read_repo', 'read_metrics', 'run_tests', 'run_analysis', 'web_research', 'consult_model',
  ]),
  DRAFT: Object.freeze([
    'write_draft', 'write_report', 'write_decision_doc', 'update_state',
    // Writing an outreach email to a file. Deliberately DRAFT and not CONTACT_EXTERNAL: it makes
    // no contact, and filing it under the never-granted capability would have forced that
    // capability open — the rot that starts every "we only widened it slightly" story. Sending
    // stays impossible the honest way: this repository has no transport. See ceo-outreach.mjs.
    'write_outreach_draft',
  ]),
  MUTATE_BRANCH: Object.freeze([
    'create_branch', 'commit_to_branch', 'open_pull_request', 'write_repo_file',
  ]),
  MUTATE_PROD: Object.freeze([
    'merge_pull_request', 'deploy',
  ]),
  CONTACT_EXTERNAL: Object.freeze([]),
  SPEND: Object.freeze([]),
});

/**
 * Actions withdrawn while LOOP_UNATTENDED=1. Everything shipping-shaped needs a human awake:
 * the operator and the reviewers are asleep, so the loop may author but never land.
 */
export const UNATTENDED_WITHDRAWN = Object.freeze(['merge_pull_request', 'deploy']);

const KNOWN_CAPABILITIES = new Set(Object.values(CAPABILITIES));
const NEVER_GRANTED = new Set([CAPABILITIES.CONTACT_EXTERNAL, CAPABILITIES.SPEND]);

/**
 * Halt, twice over.
 *
 * `process.exit` is the house convention and is not catchable, so in ordinary Node this ends it.
 * But a long-running agent harness may stub `process.exit` so one rejected sub-step doesn't kill
 * the host process — and the previous version then simply FELL THROUGH and let the caller perform
 * the forbidden action (security review, CRITICAL 2). The throw after it is unreachable in normal
 * execution and load-bearing when exit has been neutered.
 */
function abort(detail) {
  const message = `[ceo-guard] ${detail} Aborting.`;
  console.error(message);
  process.exit(1);
  throw new CeoGuardAbort(message);
}

/** Exact-match only. No normalisation, no fuzzy matching — that was the bug. */
function isKnownAction(capability, action) {
  const allowed = ALLOWED[capability];
  return Array.isArray(allowed) && allowed.includes(action);
}

function normalizeBranch(branch) {
  if (typeof branch !== 'string') return null;
  const trimmed = branch.trim().replace(/^refs\/heads\//, '');
  return trimmed === '' ? null : trimmed.toLowerCase();
}

/** Actions that land code somewhere and therefore need a branch checked. */
const BRANCH_SCOPED = new Set(['commit_to_branch', 'open_pull_request', 'merge_pull_request']);

/**
 * Gate one orchestrator action.
 *
 * Fail-closed at every step: unknown capability, unknown action, never-granted capability,
 * withdrawn-while-unattended, protected branch, and — the review's CRITICAL 3 — a branch-scoped
 * action whose branch is missing or unresolvable.
 */
export function assertActionAllowed({ capability, action, branch } = {}) {
  if (!KNOWN_CAPABILITIES.has(capability)) {
    const label = capability === undefined ? '(missing)' : JSON.stringify(capability);
    abort(`action ${JSON.stringify(action ?? null)} carries unknown capability ${label}.`);
  }

  if (NEVER_GRANTED.has(capability)) {
    abort(`capability ${capability} is never granted to the orchestrator.`);
  }

  if (typeof action !== 'string' || !isKnownAction(capability, action)) {
    abort(
      `action ${JSON.stringify(action ?? null)} is not on the allowlist for ${capability}. ` +
        `Permitted: [${ALLOWED[capability].join(', ') || 'none'}].`,
    );
  }

  if (process.env.LOOP_UNATTENDED === '1' && UNATTENDED_WITHDRAWN.includes(action)) {
    abort(`${action} is withdrawn during the unattended loop (LOOP_UNATTENDED=1).`);
  }

  if (BRANCH_SCOPED.has(action)) {
    const target = normalizeBranch(branch);
    if (target === null) {
      // An unknown branch used to pass. Unknown must abort, exactly as an unknown capability does.
      abort(`${action} requires an explicit branch; got ${JSON.stringify(branch ?? null)}.`);
    }
    if (PROTECTED_BRANCHES.includes(target)) {
      abort(`${action} targets protected branch "${target}".`);
    }
  }
}

// ---------------------------------------------------------------------------
// State protection
// ---------------------------------------------------------------------------

/**
 * Fields the orchestrator may never rewrite.
 *
 * `objective` and `kill_criterion` are the operator's goalposts. `modules` is here because
 * flipping a dormant module (`exit`, `hiring`) to active is the agent granting itself new scope —
 * a goalpost move in substance (review HIGH 4).
 *
 * `metrics` is here for a sharper reason: the kill criterion trips by comparing `metrics.wau`
 * against `kill_criterion.wau_threshold`. An agent that writes its own metrics can silence the
 * kill switch without ever touching the field the guard watches. Measurements therefore do NOT
 * come through the agent path at all — see assertMeasurementUpdate.
 */
export const AGENT_PROTECTED_FIELDS = Object.freeze([
  // `repo` joins them because it is what scopes a pr_sha. An agent that could rewrite it could
  // point the evidence rule at a repository whose shas it controls, and every "shipped" claim
  // would verify against work nobody asked for.
  'repo', 'objective', 'kill_criterion', 'modules', 'metrics',
]);

/** Only these may differ on a measurement write. */
const MEASUREMENT_WRITABLE = Object.freeze(['metrics', 'cycle']);

function assertBothValid(previousState, nextState) {
  // Previously these were compared with optional chaining, so assertStateMutationAllowed({}, {})
  // passed silently — undefined === undefined on both rails (review HIGH 5). Validating first
  // means a degenerate state aborts instead of comparing equal by absence.
  assertValidCeoState(previousState);
  assertValidCeoState(nextState);
}

/**
 * The AGENT write path: everything operator-owned must be byte-identical.
 *
 * `history` cannot be on AGENT_PROTECTED_FIELDS — log() appends to it, and that is the agent path.
 * So it gets the next-strongest thing: APPEND-ONLY. The old record must survive verbatim as a prefix
 * of the new one, and at most one entry may arrive per write.
 *
 * Review finding (Codex, HIGH): without this, `history` was neither protected nor item-validated, so
 * the two rails that read it could both be defeated by editing it — delete an overdue unjudged bet's
 * cycle, or insert a fabricated improving `primary_value`, and the flat and theater detectors go
 * quiet. An append-only log is exactly as rewritable as a git history: not.
 */
export function assertStateMutationAllowed(previousState, nextState) {
  assertBothValid(previousState, nextState);
  for (const field of AGENT_PROTECTED_FIELDS) {
    if (!isDeepStrictEqual(previousState[field], nextState[field])) {
      abort(`${field} mutation is not permitted on the agent write path.`);
    }
  }

  const before = previousState.history;
  const after = nextState.history;

  if (after.length < before.length) {
    abort(
      `history shrank from ${before.length} to ${after.length} entries. It is append-only — ` +
        'the record of what happened is not a draft.',
    );
  }
  if (after.length > before.length + 1) {
    abort(
      `history grew by ${after.length - before.length} entries in one write; a cycle logs exactly one.`,
    );
  }
  for (let index = 0; index < before.length; index += 1) {
    if (!isDeepStrictEqual(before[index], after[index])) {
      abort(
        `history entry ${index} (cycle ${before[index]?.cycle ?? '?'}) was rewritten. Past cycles ` +
          'are immutable; a wrong entry is corrected by a later one, not by editing it away.',
      );
    }
  }
}

/**
 * The MEASUREMENT write path: metrics come from an independent measurement step, never from the
 * agent's proposed next state. Anything other than metrics/cycle changing here means the caller
 * smuggled agent-authored edits through the measurement door.
 */
export function assertMeasurementUpdate(previousState, nextState) {
  assertBothValid(previousState, nextState);
  for (const key of Object.keys(previousState)) {
    if (MEASUREMENT_WRITABLE.includes(key)) continue;
    if (!isDeepStrictEqual(previousState[key], nextState[key])) {
      abort(`${key} changed on the measurement path; only [${MEASUREMENT_WRITABLE.join(', ')}] may.`);
    }
  }
}
