/**
 * db:load-dump — load a production dump into STAGING, with the emails sanitized.
 *
 * This is A4 step 5, the last piece `db:reset-staging` delegates: staging is disposable BY
 * CONSTRUCTION, and "disposable" is only true if there is a rebuild path. Bootstrap gives it the
 * schema; this gives it the data.
 *
 * WHAT IS SANITIZED, AND WHAT IS NOT. `auth.users.email` becomes `user-<n>@example.invalid`.
 * EVERYTHING ELSE IS VERBATIM — `id` and `encrypted_password` above all, because a rebuild that
 * drops the password hashes produces accounts nobody can sign in to, which is indistinguishable
 * from having lost them, and every foreign key in the database points at those ids.
 *
 * IT WILL NOT RUN AGAINST PRODUCTION. The target is certified before a socket is opened, the
 * production ref is refused outright, and only a ref deriving the label `staging` is accepted —
 * `HARNESS_DB_WRITE_OK` does not unlock production here, because consent is necessary and never
 * sufficient. The consent value is read from the SHELL, snapshotted before any file is loaded, so a
 * `--secrets-file` cannot grant its own approval (round-5 regression, same shape as the reset).
 *
 * Usage:
 *   npx tsx scripts/db-load-dump.mts --dump <path> [--secrets-file <p>]        # DRY RUN
 *   HARNESS_DB_WRITE_OK=<staging-ref> npx tsx scripts/db-load-dump.mts \
 *     --dump <path> --secrets-file <p> --replace --execute
 *
 * Exit codes: 0 planned or loaded · 1 a step failed · 2 refused (identity, consent, or target)
 */
import { existsSync, readFileSync } from 'node:fs';

import pg from 'pg';

import { readClassification } from './lib/classification';
import { residualAddresses, sanitizeUserTables } from './lib/dumpSanitize';
import { TargetRefusal } from './lib/migration-target-guard';
import { certify, readCounts, WhoamiConnectionError } from './lib/whoami';

/** Snapshotted before any dotenv load — a secrets file must not be able to consent for itself. */
const SHELL_WRITE_CONSENT = (process.env.HARNESS_DB_WRITE_OK ?? '').trim().toLowerCase();

const EXECUTE = process.argv.includes('--execute');
const REPLACE = process.argv.includes('--replace');

function fail(message: string, code: number): never {
  process.stderr.write(`[db:load-dump] ${message}\n`);
  process.exit(code);
}

function arg(name: string): string | null {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] ?? '' : null;
}

/**
 * The load order. Parents before children, because the dump preserves real ids and real foreign
 * keys: `auth.users` must exist before anything that references a user, and `public.bars` before
 * anything that references a bar. Tables not named here follow, in the dump's own order.
 */
const FIRST = ['auth.users', 'auth.identities', 'public.profiles', 'public.bars'];

/**
 * TABLES THIS TOOL WILL NOT LOAD, WHATEVER THE DUMP CONTAINS.
 *
 * The two LEDGERS are owned by the migration chain, not by the data: staging has 64 rows because
 * B3 applied 64 migrations, and production has 33 because it stopped at 0032. Copying production's
 * ledger over would leave staging claiming a schema it does not have — the dry run showed exactly
 * that, on a target whose ledger had just been proved.
 *
 * The auth SESSION tables are live credentials for production accounts. A staging rebuild wants the
 * users, not their open sessions and refresh tokens; importing those grants working production
 * sessions inside staging, and they are regenerated by signing in anyway.
 *
 * `auth.identities` is deliberately NOT here: an account without its identity row cannot sign in,
 * which is the same failure as dropping the password hash.
 */
const NEVER_LOAD = new Set([
  'public.schema_migrations',
  'auth.schema_migrations',
  'auth.sessions',
  'auth.refresh_tokens',
  'auth.one_time_tokens',
  'auth.flow_state',
  'auth.mfa_amr_claims',
]);

interface Dump {
  ref: string;
  taken_at: string;
  tables: Record<string, Record<string, unknown>[]>;
}

async function main(): Promise<void> {
  const dumpPath = arg('--dump');
  const secretsFile = arg('--secrets-file');
  if (!dumpPath) fail('--dump <path> is required', 2);
  if (!existsSync(dumpPath)) fail(`--dump ${dumpPath} does not exist`, 2);

  // ── IDENTITY, BEFORE ANY SOCKET ──────────────────────────────────────────────────────────────
  const productionRef = readClassification().productionRef as string;
  const identity = await certify(secretsFile);
  if (identity.refusals.length > 0) {
    for (const reason of identity.refusals) process.stderr.write(`[db:load-dump] ${reason}\n`);
    fail('the target was refused — nothing is loaded into an unidentified database', 2);
  }
  const { certified, ref, label } = identity;

  if (ref === productionRef) {
    fail(
      `REFUSED: ${ref} is the PRODUCTION project. This tool writes rows into the database it is `
      + 'pointed at and will not run against production under any circumstances.',
      2,
    );
  }
  if (label !== 'staging') {
    fail(`REFUSED: ${ref} derives the label "${label}", not "staging". Only staging is rebuilt.`, 2);
  }
  if (EXECUTE && SHELL_WRITE_CONSENT !== ref) {
    fail(
      SHELL_WRITE_CONSENT
        ? `REFUSED: HARNESS_DB_WRITE_OK is "${SHELL_WRITE_CONSENT}" but the target is ${ref}.`
        : `REFUSED: --execute requires HARNESS_DB_WRITE_OK=${ref} in the shell. The operator types it, per act.`,
      2,
    );
  }

  const dump = JSON.parse(readFileSync(dumpPath, 'utf8')) as Dump;
  if (dump.ref !== productionRef) {
    fail(
      `REFUSED: the dump names project ${dump.ref}, which is not the declared production ref `
      + `${productionRef}. This tool rebuilds staging FROM production and will not load an `
      + 'unidentified snapshot.',
      2,
    );
  }

  process.stdout.write(`source dump : ${dumpPath}\n`);
  process.stdout.write(`            : ${dump.ref} taken_at ${dump.taken_at}\n`);
  process.stdout.write(`target      : ${ref} (${label})\n\n`);

  // SANITIZE ONCE, UP FRONT, ACROSS TABLES — auth.identities has to be given the same address as
  // the auth.users row it belongs to, so neither can be sanitized alone.
  const sanitized = sanitizeUserTables(dump.tables);

  const names = Object.keys(sanitized);
  const ordered = [...FIRST.filter((t) => names.includes(t)), ...names.filter((t) => !FIRST.includes(t))];
  const excluded = ordered.filter((t) => NEVER_LOAD.has(t) && (sanitized[t] ?? []).length > 0);
  const candidates = ordered.filter((t) => !NEVER_LOAD.has(t) && (sanitized[t] ?? []).length > 0);

  const client = new pg.Client({ connectionString: certified.connectionString });
  try {
    await client.connect();
  } catch (error) {
    fail(`could not connect: ${(error as Error).message}`, 1);
  }

  // A table the target does not have is SKIPPED AND NAMED, never a failed insert that rolls the
  // whole rebuild back. The V8 schema legitimately drops tables production still carries.
  const absent: string[] = [];
  const nonEmpty: string[] = [];
  /** Per table: the columns the TARGET will actually accept in an INSERT. */
  const insertable = new Map<string, Set<string>>();
  /** Per table: dump columns the target will not take, and why, so a skip is never silent. */
  const dropped = new Map<string, string[]>();
  /** Per table: the json/jsonb columns, which have to be sent as text rather than as JS values. */
  const jsonColumns = new Map<string, Set<string>>();
  try {
    for (const table of candidates) {
      const [schema, name] = table.split('.');
      const columns = await client.query<{
        column_name: string; is_generated: string; identity_generation: string | null; data_type: string;
      }>(
        'select column_name, is_generated, identity_generation, data_type'
        + ' from information_schema.columns'
        + ' where table_schema = $1 and table_name = $2',
        [schema, name],
      );
      if (columns.rows.length === 0) {
        absent.push(table);
        continue;
      }
      nonEmpty.push(table);

      // GENERATED AND IDENTITY-ALWAYS COLUMNS CANNOT BE WRITTEN AT ALL. `auth.users.confirmed_at`
      // is generated, and naming it in an INSERT fails the statement — which, inside the single
      // transaction this tool uses, rolls the ENTIRE rebuild back. B4 died there on its first run.
      // Postgres decides what is insertable, not this script's idea of the schema.
      const accepts = new Set(
        columns.rows
          .filter((c) => c.is_generated !== 'ALWAYS' && c.identity_generation !== 'ALWAYS')
          .map((c) => c.column_name),
      );
      insertable.set(table, accepts);

      // JSON COLUMNS MUST BE SENT AS TEXT. node-pg turns a JS array into a POSTGRES ARRAY literal
      // ({"a","b"}), which a json/jsonb column rejects with "Expected \":\", but found \",\"" — B4's
      // third failure, on a bars column holding a JSON array. The catalog already tells us the
      // type, so the encoding follows from it rather than from guessing at the value's shape.
      jsonColumns.set(
        table,
        new Set(columns.rows.filter((c) => c.data_type === 'json' || c.data_type === 'jsonb')
          .map((c) => c.column_name)),
      );

      const dumpColumns = Object.keys((sanitized[table] ?? [])[0] ?? {});
      const skipped = dumpColumns
        .filter((c) => !accepts.has(c))
        .map((c) => (columns.rows.some((row) => row.column_name === c)
          ? c + ' (generated)'
          : c + ' (not in the V8 schema)'));
      if (skipped.length > 0) dropped.set(table, skipped);
    }

    // ── THE PLAN ───────────────────────────────────────────────────────────────────────────────
    process.stdout.write('would load:\n');
    for (const table of nonEmpty) {
      const rows = sanitized[table] ?? [];
      process.stdout.write(`  ${table.padEnd(34)}${String(rows.length).padStart(6)}`);
      if (table === 'auth.users' || table === 'auth.identities') {
        process.stdout.write('   addresses -> user-<n>@example.invalid');
      }
      process.stdout.write('\n');
      const residual = residualAddresses(rows);
      if (residual.length > 0) {
        process.stdout.write(`  ${''.padEnd(34)}       ! STILL CARRIES AN ADDRESS: ${residual.join(', ')}\n`);
      }
      const skipped = dropped.get(table);
      if (skipped && skipped.length > 0) {
        process.stdout.write(`  ${''.padEnd(34)}       columns not written: ${skipped.join(', ')}\n`);
      }
    }

    if (excluded.length > 0) {
      process.stdout.write('\nexcluded by policy (ledgers and live auth sessions):\n');
      for (const table of excluded) {
        process.stdout.write(`  ${table.padEnd(34)}${String((sanitized[table] ?? []).length).padStart(6)}\n`);
      }
    }
    if (absent.length > 0) {
      process.stdout.write('\nabsent from the target schema, skipped:\n');
      for (const table of absent) {
        process.stdout.write(`  ${table.padEnd(34)}${String((sanitized[table] ?? []).length).padStart(6)} row(s) in the dump\n`);
      }
    }
    const empty = ordered.filter((t) => (sanitized[t] ?? []).length === 0);
    if (empty.length > 0) process.stdout.write(`\nempty in the dump (${empty.length}): ${empty.join(', ')}\n`);

    process.stdout.write('\ncurrently in the target:\n');
    for (const table of nonEmpty) {
      let live = 'n/a';
      try {
        const r = await client.query(`select count(*)::int n from ${table.split('.').map((p) => `"${p}"`).join('.')}`);
        live = String(r.rows[0]?.n ?? 0);
      } catch { live = 'no such table'; }
      process.stdout.write(`  ${table.padEnd(34)}${live.padStart(6)}\n`);
    }

    if (!EXECUTE) {
      process.stdout.write(
        `\nDRY RUN — nothing was written.\n`
        + `To load:  HARNESS_DB_WRITE_OK=${ref} npx tsx scripts/db-load-dump.mts --dump <path>`
        + `${secretsFile ? ` --secrets-file ${secretsFile}` : ''} --replace --execute\n`
        + '--replace is required and means exactly what it says: each table listed above is emptied\n'
        + "before its rows are inserted, so the bootstrap's fixture rows do not collide with the\n"
        + 'real ones. Without it this tool refuses rather than guessing at a merge.\n',
      );
      return;
    }

    if (!REPLACE) {
      fail(
        '--execute requires --replace. The target already holds bootstrap fixture rows, and merging '
        + 'them with production rows is a decision this tool will not make silently.',
        2,
      );
    }

    // ── LOAD ─────────────────────────────────────────────────────────────────────────────────
    // One transaction: a partial rebuild is worse than none, because it looks finished.
    await client.query('begin');
    try {
      for (const table of [...nonEmpty].reverse()) {
        const quoted = table.split('.').map((p) => `"${p}"`).join('.');
        await client.query(`delete from ${quoted}`);
      }
      for (const table of nonEmpty) {
        const rows = sanitized[table] ?? [];
        const quoted = table.split('.').map((p) => `"${p}"`).join('.');
        // CLEAR IT AGAIN, IMMEDIATELY BEFORE INSERTING. The bulk delete above ran before any row
        // existed; inserting auth.users then FIRES public.handle_new_user (0001, trigger
        // on_auth_user_created), which writes a profile per user INSIDE this transaction. B4 died
        // on that duplicate key. The dump's row is the one that should survive, so the
        // trigger's placeholder is removed rather than merged with.
        await client.query(`delete from ${quoted}`);
        const accepts = insertable.get(table) ?? new Set<string>();
        const columns = Object.keys(rows[0] ?? {}).filter((c) => accepts.has(c));
        if (columns.length === 0) continue;
        const columnList = columns.map((c) => `"${c}"`).join(', ');
        const asJson = jsonColumns.get(table) ?? new Set<string>();
        for (const row of rows) {
          const values = columns.map((c) => {
            const value = row[c] ?? null;
            if (value === null) return null;
            return asJson.has(c) && typeof value === 'object' ? JSON.stringify(value) : value;
          });
          const placeholders = columns.map((_, i) => `$${i + 1}`).join(', ');
          await client.query(`insert into ${quoted} (${columnList}) values (${placeholders})`, values);
        }
        process.stdout.write(`  loaded ${table.padEnd(34)}${String(rows.length).padStart(6)}\n`);
      }
      await client.query('commit');
    } catch (error) {
      await client.query('rollback').catch(() => {});
      throw error;
    }
  } finally {
    await client.end();
  }

  const after = await readCounts(identity);
  process.stdout.write(`\n${after.line}\n`);
}

try {
  await main();
} catch (error) {
  if (error instanceof WhoamiConnectionError) fail(error.message, 1);
  if (error instanceof TargetRefusal) fail(`REFUSED: ${error.message}`, 2);
  throw error;
}
