import { sha256Of } from './checkpoint';
import type { NormalizedCandidate } from './types';

/**
 * ATTENDED apply path — the census's sole write path. Structure (design
 * review, GLM+DeepSeek): the dry-run report is bound by an apply-sidecar
 * (payload sha256 + configHash + codeSha); curation may transform candidates
 * into catalog rows, but every curated row must cite the externalId of a
 * candidate in the EXACT report the operator reviewed. Tampered reports,
 * fabricated rows, stale reports, and unattended invocations are all typed
 * refusals BEFORE any client is constructed.
 */

export interface ApplySidecar {
  runId: string;
  payloadSha256: string;
  configHash: string;
  codeSha: string;
  generatedAt: string;
}

// NOTE (T0 review of f5d1579, Codex H2 + DeepSeek TOCTOU, both confirmed):
// a `rebindCodeSha` primitive briefly lived here to re-point a dirty-tree
// codeSha at a later clean commit. It could not PROVE byte identity between
// the generation tree and the rebind target (any clean-A sidecar could be
// rebound to unrelated clean-B), so it was removed the same night. The
// sound procedure is: commit first, then RE-RUN the census at the clean
// SHA so the sidecar is natively bound to immutable code. Do not
// reintroduce a rebind without a persisted, verifiable content-tree digest
// captured at generation time.

export interface CuratedCandidate {
  id: string;
  externalId: string;
  name: string;
  neighborhood: string;
  address: string;
  lat: number;
  lng: number;
  priceTier: number;
  tags: string[];
  blurb: string;
  lastVerified: string;
}

export type ApplyRefusal =
  | 'unattended'
  | 'payload_hash'
  | 'code_drift'
  | 'stale_report'
  | `unknown_provenance:${string}`;

export function checkApplyPreconditions(input: {
  unattended: boolean;
  sidecar: ApplySidecar;
  reportCandidates: NormalizedCandidate[];
  curated: CuratedCandidate[];
  maxAgeDays: number;
  now: Date;
  /** Current git HEAD; refuse when generation code differs (santa round-2). */
  currentCodeSha: string;
  /** Attended operator override after reviewing what changed. */
  allowCodeDrift?: boolean;
}): { ok: true } | { ok: false; reason: ApplyRefusal } {
  if (input.unattended) return { ok: false, reason: 'unattended' };
  if (sha256Of(JSON.stringify(input.reportCandidates)) !== input.sidecar.payloadSha256) {
    return { ok: false, reason: 'payload_hash' };
  }
  // The report was generated by a specific code version; applying it under
  // different generation logic (dedup keys, evidence rules, tile maps) is
  // refused unless the operator explicitly reviewed the drift. configHash
  // has no apply-time counterpart (it is bound INTO the payload identity
  // above); codeSha is the enforceable half of the sidecar's promise.
  if (!input.allowCodeDrift && input.sidecar.codeSha !== input.currentCodeSha) {
    return { ok: false, reason: 'code_drift' };
  }
  // FAIL CLOSED on malformed inputs (Codex review): NaN compares false
  // against everything, so a typo'd --max-age-days or an invalid
  // generatedAt would otherwise wave an arbitrarily old report through.
  const ageMs = input.now.getTime() - new Date(input.sidecar.generatedAt).getTime();
  const maxAgeMs = input.maxAgeDays * 24 * 60 * 60 * 1000;
  if (!Number.isFinite(ageMs) || !Number.isFinite(maxAgeMs) || ageMs > maxAgeMs) {
    return { ok: false, reason: 'stale_report' };
  }
  const known = new Set(input.reportCandidates.map((c) => c.externalId));
  for (const row of input.curated) {
    if (!known.has(row.externalId)) {
      return { ok: false, reason: `unknown_provenance:${row.externalId}` };
    }
  }
  return { ok: true };
}

/**
 * Minimal client surface so the insert loop is unit-testable without a
 * database. The real caller passes a supabase-js client.
 */
export interface BarsWriteClient {
  selectExisting(from: number, to: number): Promise<{
    data: Array<{ id: string; name: string; neighborhood: string }> | null;
    error: { message: string } | null;
  }>;
  insert(rows: Array<Record<string, unknown>>): Promise<{ error: { message: string } | null }>;
}

export function assertProjectRef(url: string, expectedRef: string): void {
  const host = new URL(url).hostname;
  if (host !== `${expectedRef}.supabase.co`) {
    throw new Error(`refusing Supabase host ${host}; expected ${expectedRef}.supabase.co`);
  }
}

const normalizeLegacy = (s: string): string =>
  s
    .toLowerCase()
    .replace(/['’.&]/g, '')
    .replace(/\band\b|\bthe\b/g, '')
    .replace(/\s+/g, ' ')
    .trim();

/**
 * Paginated existing-rows read (PostgREST silently caps at 1,000), id and
 * name+neighborhood dedup, then one atomic insert of at most 50 rows.
 * Database errors fail the entire batch; row-by-row fallback would make the
 * reviewed payload and its rollback counts untruthful.
 */
export async function applyCurated(
  client: BarsWriteClient,
  curated: CuratedCandidate[],
  validateRow: (row: Record<string, unknown>) => boolean,
): Promise<{ inserted: number; rejected: Array<{ id: string; reason: string }> }> {
  const existing: Array<{ id: string; name: string; neighborhood: string }> = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await client.selectExisting(from, from + 999);
    if (error || !data) throw new Error(`failed to read existing bars: ${error?.message}`);
    existing.push(...data);
    if (data.length < 1000) break;
  }
  const existingIds = new Set(existing.map((b) => b.id));
  const existingNameHood = new Set(
    existing.map((b) => `${normalizeLegacy(b.name)}|${b.neighborhood}`),
  );

  const rejected: Array<{ id: string; reason: string }> = [];
  const accepted: Array<Record<string, unknown>> = [];
  for (const c of curated) {
    const row: Record<string, unknown> = {
      id: c.id,
      name: c.name,
      lat: c.lat,
      lng: c.lng,
      tags: c.tags,
      neighborhood: c.neighborhood,
      price_tier: c.priceTier,
      hours: null,
      blurb: c.blurb,
      address: c.address,
      place_id: null,
      business_status: null,
      photo_count: 0,
      photo_attributions: null,
      reviews: null,
      last_verified: c.lastVerified,
      source: 'census',
    };
    if (!validateRow(row)) {
      rejected.push({ id: c.id, reason: 'boundary validation failed' });
      continue;
    }
    if (existingIds.has(c.id)) {
      rejected.push({ id: c.id, reason: 'id already exists' });
      continue;
    }
    const nh = `${normalizeLegacy(c.name)}|${c.neighborhood}`;
    if (existingNameHood.has(nh)) {
      rejected.push({ id: c.id, reason: 'name+neighborhood duplicate' });
      continue;
    }
    existingIds.add(c.id);
    existingNameHood.add(nh);
    accepted.push(row);
  }

  if (accepted.length > 50) throw new Error(`atomic batch limit exceeded: ${accepted.length}`);
  if (accepted.length > 0) {
    const { error } = await client.insert(accepted);
    if (error) throw new Error(`atomic insert failed: ${error.message}`);
  }
  return { inserted: accepted.length, rejected };
}
